HEADERS += \
           $$PWD/PythonQtWrapper_QAbstractItemModel.h \
           $$PWD/PythonQtWrapper_QAbstractListModel.h \
           $$PWD/PythonQtWrapper_QAbstractTableModel.h \
           $$PWD/PythonQtWrapper_QBasicTimer.h \
           $$PWD/PythonQtWrapper_QBitArray.h \
           $$PWD/PythonQtWrapper_QBuffer.h \
           $$PWD/PythonQtWrapper_QByteArray.h \
           $$PWD/PythonQtWrapper_QByteArrayMatcher.h \
           $$PWD/PythonQtWrapper_QChildEvent.h \
           $$PWD/PythonQtWrapper_QCoreApplication.h \
           $$PWD/PythonQtWrapper_QCryptographicHash.h \
           $$PWD/PythonQtWrapper_QDataStream.h \
           $$PWD/PythonQtWrapper_QDir.h \
           $$PWD/PythonQtWrapper_QDirIterator.h \
           $$PWD/PythonQtWrapper_QDynamicPropertyChangeEvent.h \
           $$PWD/PythonQtWrapper_QEvent.h \
           $$PWD/PythonQtWrapper_QEventLoop.h \
           $$PWD/PythonQtWrapper_QFile.h \
           $$PWD/PythonQtWrapper_QFileInfo.h \
           $$PWD/PythonQtWrapper_QFileSystemWatcher.h \
           $$PWD/PythonQtWrapper_QIODevice.h \
           $$PWD/PythonQtWrapper_QLibraryInfo.h \
           $$PWD/PythonQtWrapper_QMimeData.h \
           $$PWD/PythonQtWrapper_QModelIndex.h \
           $$PWD/PythonQtWrapper_QMutex.h \
           $$PWD/PythonQtWrapper_QObject.h \
           $$PWD/PythonQtWrapper_QPersistentModelIndex.h \
           $$PWD/PythonQtWrapper_QProcess.h \
           $$PWD/PythonQtWrapper_QRunnable.h \
           $$PWD/PythonQtWrapper_QSemaphore.h \
           $$PWD/PythonQtWrapper_QSettings.h \
           $$PWD/PythonQtWrapper_QSignalMapper.h \
           $$PWD/PythonQtWrapper_QSocketNotifier.h \
           $$PWD/PythonQtWrapper_QStringMatcher.h \
           $$PWD/PythonQtWrapper_QSystemSemaphore.h \
           $$PWD/PythonQtWrapper_QTemporaryFile.h \
           $$PWD/PythonQtWrapper_QTextBoundaryFinder.h \
           $$PWD/PythonQtWrapper_QTextCodec.h \
           $$PWD/PythonQtWrapper_QTextCodecPlugin.h \
           $$PWD/PythonQtWrapper_QTextDecoder.h \
           $$PWD/PythonQtWrapper_QTextEncoder.h \
           $$PWD/PythonQtWrapper_QTextStream.h \
           $$PWD/PythonQtWrapper_QThreadPool.h \
           $$PWD/PythonQtWrapper_QTimeLine.h \
           $$PWD/PythonQtWrapper_QTimer.h \
           $$PWD/PythonQtWrapper_QTimerEvent.h \
           $$PWD/PythonQtWrapper_QTranslator.h \
           $$PWD/PythonQtWrapper_QUuid.h \
           $$PWD/PythonQtWrapper_QWaitCondition.h \
           $$PWD/PythonQtWrapper_QXmlStreamAttribute.h \
           $$PWD/PythonQtWrapper_QXmlStreamAttributes.h \
           $$PWD/PythonQtWrapper_QXmlStreamEntityDeclaration.h \
           $$PWD/PythonQtWrapper_QXmlStreamEntityResolver.h \
           $$PWD/PythonQtWrapper_QXmlStreamNamespaceDeclaration.h \
           $$PWD/PythonQtWrapper_QXmlStreamNotationDeclaration.h \
           $$PWD/PythonQtWrapper_QXmlStreamReader.h \
           $$PWD/PythonQtWrapper_QXmlStreamWriter.h \
           $$PWD/PythonQtWrapper_QtConcurrent.h \

SOURCES += \
           $$PWD/PythonQtWrapper_QAbstractItemModel.cpp \
           $$PWD/PythonQtWrapper_QAbstractListModel.cpp \
           $$PWD/PythonQtWrapper_QAbstractTableModel.cpp \
           $$PWD/PythonQtWrapper_QBasicTimer.cpp \
           $$PWD/PythonQtWrapper_QBitArray.cpp \
           $$PWD/PythonQtWrapper_QBuffer.cpp \
           $$PWD/PythonQtWrapper_QByteArray.cpp \
           $$PWD/PythonQtWrapper_QByteArrayMatcher.cpp \
           $$PWD/PythonQtWrapper_QChildEvent.cpp \
           $$PWD/PythonQtWrapper_QCoreApplication.cpp \
           $$PWD/PythonQtWrapper_QCryptographicHash.cpp \
           $$PWD/PythonQtWrapper_QDataStream.cpp \
           $$PWD/PythonQtWrapper_QDir.cpp \
           $$PWD/PythonQtWrapper_QDirIterator.cpp \
           $$PWD/PythonQtWrapper_QDynamicPropertyChangeEvent.cpp \
           $$PWD/PythonQtWrapper_QEvent.cpp \
           $$PWD/PythonQtWrapper_QEventLoop.cpp \
           $$PWD/PythonQtWrapper_QFile.cpp \
           $$PWD/PythonQtWrapper_QFileInfo.cpp \
           $$PWD/PythonQtWrapper_QFileSystemWatcher.cpp \
           $$PWD/PythonQtWrapper_QIODevice.cpp \
           $$PWD/PythonQtWrapper_QLibraryInfo.cpp \
           $$PWD/PythonQtWrapper_QMimeData.cpp \
           $$PWD/PythonQtWrapper_QModelIndex.cpp \
           $$PWD/PythonQtWrapper_QMutex.cpp \
           $$PWD/PythonQtWrapper_QObject.cpp \
           $$PWD/PythonQtWrapper_QPersistentModelIndex.cpp \
           $$PWD/PythonQtWrapper_QProcess.cpp \
           $$PWD/PythonQtWrapper_QRunnable.cpp \
           $$PWD/PythonQtWrapper_QSemaphore.cpp \
           $$PWD/PythonQtWrapper_QSettings.cpp \
           $$PWD/PythonQtWrapper_QSignalMapper.cpp \
           $$PWD/PythonQtWrapper_QSocketNotifier.cpp \
           $$PWD/PythonQtWrapper_QStringMatcher.cpp \
           $$PWD/PythonQtWrapper_QSystemSemaphore.cpp \
           $$PWD/PythonQtWrapper_QTemporaryFile.cpp \
           $$PWD/PythonQtWrapper_QTextBoundaryFinder.cpp \
           $$PWD/PythonQtWrapper_QTextCodec.cpp \
           $$PWD/PythonQtWrapper_QTextCodecPlugin.cpp \
           $$PWD/PythonQtWrapper_QTextDecoder.cpp \
           $$PWD/PythonQtWrapper_QTextEncoder.cpp \
           $$PWD/PythonQtWrapper_QTextStream.cpp \
           $$PWD/PythonQtWrapper_QThreadPool.cpp \
           $$PWD/PythonQtWrapper_QTimeLine.cpp \
           $$PWD/PythonQtWrapper_QTimer.cpp \
           $$PWD/PythonQtWrapper_QTimerEvent.cpp \
           $$PWD/PythonQtWrapper_QTranslator.cpp \
           $$PWD/PythonQtWrapper_QUuid.cpp \
           $$PWD/PythonQtWrapper_QWaitCondition.cpp \
           $$PWD/PythonQtWrapper_QXmlStreamAttribute.cpp \
           $$PWD/PythonQtWrapper_QXmlStreamAttributes.cpp \
           $$PWD/PythonQtWrapper_QXmlStreamEntityDeclaration.cpp \
           $$PWD/PythonQtWrapper_QXmlStreamEntityResolver.cpp \
           $$PWD/PythonQtWrapper_QXmlStreamNamespaceDeclaration.cpp \
           $$PWD/PythonQtWrapper_QXmlStreamNotationDeclaration.cpp \
           $$PWD/PythonQtWrapper_QXmlStreamReader.cpp \
           $$PWD/PythonQtWrapper_QXmlStreamWriter.cpp \
           $$PWD/PythonQtWrapper_QtConcurrent.cpp \
           $$PWD/com_trolltech_qt_core_init.cpp
