HEADERS += \
           $$PWD/PythonQtWrapper_QDomAttr.h \
           $$PWD/PythonQtWrapper_QDomCDATASection.h \
           $$PWD/PythonQtWrapper_QDomCharacterData.h \
           $$PWD/PythonQtWrapper_QDomComment.h \
           $$PWD/PythonQtWrapper_QDomDocument.h \
           $$PWD/PythonQtWrapper_QDomDocumentFragment.h \
           $$PWD/PythonQtWrapper_QDomDocumentType.h \
           $$PWD/PythonQtWrapper_QDomElement.h \
           $$PWD/PythonQtWrapper_QDomEntity.h \
           $$PWD/PythonQtWrapper_QDomEntityReference.h \
           $$PWD/PythonQtWrapper_QDomImplementation.h \
           $$PWD/PythonQtWrapper_QDomNamedNodeMap.h \
           $$PWD/PythonQtWrapper_QDomNode.h \
           $$PWD/PythonQtWrapper_QDomNodeList.h \
           $$PWD/PythonQtWrapper_QDomNotation.h \
           $$PWD/PythonQtWrapper_QDomProcessingInstruction.h \
           $$PWD/PythonQtWrapper_QDomText.h \
           $$PWD/PythonQtWrapper_QXmlAttributes.h \
           $$PWD/PythonQtWrapper_QXmlContentHandler.h \
           $$PWD/PythonQtWrapper_QXmlDTDHandler.h \
           $$PWD/PythonQtWrapper_QXmlDeclHandler.h \
           $$PWD/PythonQtWrapper_QXmlDefaultHandler.h \
           $$PWD/PythonQtWrapper_QXmlEntityResolver.h \
           $$PWD/PythonQtWrapper_QXmlErrorHandler.h \
           $$PWD/PythonQtWrapper_QXmlInputSource.h \
           $$PWD/PythonQtWrapper_QXmlLexicalHandler.h \
           $$PWD/PythonQtWrapper_QXmlLocator.h \
           $$PWD/PythonQtWrapper_QXmlParseException.h \
           $$PWD/PythonQtWrapper_QXmlReader.h \
           $$PWD/PythonQtWrapper_QXmlSimpleReader.h \

SOURCES += \
           $$PWD/PythonQtWrapper_QDomAttr.cpp \
           $$PWD/PythonQtWrapper_QDomCDATASection.cpp \
           $$PWD/PythonQtWrapper_QDomCharacterData.cpp \
           $$PWD/PythonQtWrapper_QDomComment.cpp \
           $$PWD/PythonQtWrapper_QDomDocument.cpp \
           $$PWD/PythonQtWrapper_QDomDocumentFragment.cpp \
           $$PWD/PythonQtWrapper_QDomDocumentType.cpp \
           $$PWD/PythonQtWrapper_QDomElement.cpp \
           $$PWD/PythonQtWrapper_QDomEntity.cpp \
           $$PWD/PythonQtWrapper_QDomEntityReference.cpp \
           $$PWD/PythonQtWrapper_QDomImplementation.cpp \
           $$PWD/PythonQtWrapper_QDomNamedNodeMap.cpp \
           $$PWD/PythonQtWrapper_QDomNode.cpp \
           $$PWD/PythonQtWrapper_QDomNodeList.cpp \
           $$PWD/PythonQtWrapper_QDomNotation.cpp \
           $$PWD/PythonQtWrapper_QDomProcessingInstruction.cpp \
           $$PWD/PythonQtWrapper_QDomText.cpp \
           $$PWD/PythonQtWrapper_QXmlAttributes.cpp \
           $$PWD/PythonQtWrapper_QXmlContentHandler.cpp \
           $$PWD/PythonQtWrapper_QXmlDTDHandler.cpp \
           $$PWD/PythonQtWrapper_QXmlDeclHandler.cpp \
           $$PWD/PythonQtWrapper_QXmlDefaultHandler.cpp \
           $$PWD/PythonQtWrapper_QXmlEntityResolver.cpp \
           $$PWD/PythonQtWrapper_QXmlErrorHandler.cpp \
           $$PWD/PythonQtWrapper_QXmlInputSource.cpp \
           $$PWD/PythonQtWrapper_QXmlLexicalHandler.cpp \
           $$PWD/PythonQtWrapper_QXmlLocator.cpp \
           $$PWD/PythonQtWrapper_QXmlParseException.cpp \
           $$PWD/PythonQtWrapper_QXmlReader.cpp \
           $$PWD/PythonQtWrapper_QXmlSimpleReader.cpp \
           $$PWD/com_trolltech_qt_xml_init.cpp
