PythonQt: PythonQtThreadStateSaver Class Reference
PythonQtThreadStateSaver Class Reference
#include <PythonQtThreadSupport.h>
Public Member Functions
PythonQtThreadStateSaver ()
~PythonQtThreadStateSaver ()
void save ()
void restore ()
Detailed Description
This class wraps the Python save/restore thread state API. It can be used to allow other Python threads to run when entering C++ code from Python code.
Definition at line 104 of file PythonQtThreadSupport.h.
Constructor & Destructor Documentation
PythonQtThreadStateSaver()
PythonQtThreadStateSaver::PythonQtThreadStateSaver () inline
Definition at line 108 of file PythonQtThreadSupport.h.
{
    save();
  }
References save().
~PythonQtThreadStateSaver()
PythonQtThreadStateSaver::~PythonQtThreadStateSaver () inline
Definition at line 112 of file PythonQtThreadSupport.h.
{
    restore();
  }
References restore().
Member Function Documentation
restore()
void PythonQtThreadStateSaver::restore () inline
Definition at line 120 of file PythonQtThreadSupport.h.
                 {
    if (_state) {
      PyEval_RestoreThread(_state);
      _state = nullptr;
    }
  }
References PythonQtConvertPairToPython().
Referenced by ~PythonQtThreadStateSaver().
save()
void PythonQtThreadStateSaver::save () inline
Definition at line 116 of file PythonQtThreadSupport.h.
              {
    _state = PyEval_SaveThread();
  }
References PythonQtConvertPairToPython().
Referenced by PythonQtThreadStateSaver().
The documentation for this class was generated from the following file:
PythonQtThreadSupport.h