PythonQt: PythonQtWrapper_QMetaObject Class Reference
PythonQtWrapper_QMetaObject Class Reference
#include <PythonQtStdDecorators.h>
Public Slots
const char * getClassName (QMetaObject *obj) const
const QMetaObject * superClass (QMetaObject *obj) const
int methodOffset (QMetaObject *obj) const
int enumeratorOffset (QMetaObject *obj) const
int propertyOffset (QMetaObject *obj) const
int classInfoOffset (QMetaObject *obj) const
int constructorCount (QMetaObject *obj) const
int methodCount (QMetaObject *obj) const
int enumeratorCount (QMetaObject *obj) const
int propertyCount (QMetaObject *obj) const
int classInfoCount (QMetaObject *obj) const
int indexOfConstructor (QMetaObject *obj, const char *constructor) const
int indexOfMethod (QMetaObject *obj, const char *method) const
int indexOfSignal (QMetaObject *obj, const char *signal) const
int indexOfSlot (QMetaObject *obj, const char *slot) const
int indexOfEnumerator (QMetaObject *obj, const char *name) const
int indexOfProperty (QMetaObject *obj, const char *name) const
int indexOfClassInfo (QMetaObject *obj, const char *name) const
QMetaMethod constructor (QMetaObject *obj, int index) const
QMetaMethod method (QMetaObject *obj, int index) const
QMetaEnum enumerator (QMetaObject *obj, int index) const
QMetaProperty property (QMetaObject *obj, int index) const
QMetaClassInfo classInfo (QMetaObject *obj, int index) const
QMetaProperty userProperty (QMetaObject *obj) const
bool static_QMetaObject_checkConnectArgs (const char *signal, const char *method)
QByteArray static_QMetaObject_normalizedSignature (const char *method)
QByteArray static_QMetaObject_normalizedType (const char *type)
Detailed Description
Definition at line 175 of file PythonQtStdDecorators.h.
Member Function Documentation
classInfo
QMetaClassInfo PythonQtWrapper_QMetaObject::classInfo (QMetaObject * obj, int index) const inline slot
Definition at line 210 of file PythonQtStdDecorators.h.
{ return obj->classInfo(index); }
References PythonQtConvertPairToPython().
classInfoCount
int PythonQtWrapper_QMetaObject::classInfoCount (QMetaObject * obj) const inline slot
Definition at line 193 of file PythonQtStdDecorators.h.
{ return obj->classInfoCount(); }
References PythonQtConvertPairToPython().
classInfoOffset
int PythonQtWrapper_QMetaObject::classInfoOffset (QMetaObject * obj) const inline slot
Definition at line 187 of file PythonQtStdDecorators.h.
{ return obj->classInfoOffset(); }
References PythonQtConvertPairToPython().
constructor
QMetaMethod PythonQtWrapper_QMetaObject::constructor (QMetaObject * obj, int index) const inline slot
Definition at line 206 of file PythonQtStdDecorators.h.
{ return obj->constructor(index); }
References PythonQtConvertPairToPython().
Referenced by indexOfConstructor().
constructorCount
int PythonQtWrapper_QMetaObject::constructorCount (QMetaObject * obj) const inline slot
Definition at line 189 of file PythonQtStdDecorators.h.
{ return obj->constructorCount(); }
References PythonQtConvertPairToPython().
enumerator
QMetaEnum PythonQtWrapper_QMetaObject::enumerator (QMetaObject * obj, int index) const inline slot
Definition at line 208 of file PythonQtStdDecorators.h.
{ return obj->enumerator(index); }
References PythonQtConvertPairToPython().
enumeratorCount
int PythonQtWrapper_QMetaObject::enumeratorCount (QMetaObject * obj) const inline slot
Definition at line 191 of file PythonQtStdDecorators.h.
{ return obj->enumeratorCount(); }
References PythonQtConvertPairToPython().
enumeratorOffset
int PythonQtWrapper_QMetaObject::enumeratorOffset (QMetaObject * obj) const inline slot
Definition at line 185 of file PythonQtStdDecorators.h.
{ return obj->enumeratorOffset(); }
References PythonQtConvertPairToPython().
getClassName
const char * PythonQtWrapper_QMetaObject::getClassName (QMetaObject * obj) const inline slot
Definition at line 181 of file PythonQtStdDecorators.h.
{ return obj->className(); }
References PythonQtConvertPairToPython().
indexOfClassInfo
int PythonQtWrapper_QMetaObject::indexOfClassInfo (QMetaObject * obj, const char * name) const inline slot
Definition at line 204 of file PythonQtStdDecorators.h.
{ return obj->indexOfClassInfo(name); }
References PythonQtConvertPairToPython().
indexOfConstructor
int PythonQtWrapper_QMetaObject::indexOfConstructor (QMetaObject * obj, const char * constructor) const inline slot
Definition at line 195 of file PythonQtStdDecorators.h.
  {
    return obj->indexOfConstructor(constructor);
  }
References constructor(), and PythonQtConvertPairToPython().
indexOfEnumerator
int PythonQtWrapper_QMetaObject::indexOfEnumerator (QMetaObject * obj, const char * name) const inline slot
Definition at line 202 of file PythonQtStdDecorators.h.
{ return obj->indexOfEnumerator(name); }
References PythonQtConvertPairToPython().
indexOfMethod
int PythonQtWrapper_QMetaObject::indexOfMethod (QMetaObject * obj, const char * method) const inline slot
Definition at line 199 of file PythonQtStdDecorators.h.
{ return obj->indexOfMethod(method); }
References method(), and PythonQtConvertPairToPython().
indexOfProperty
int PythonQtWrapper_QMetaObject::indexOfProperty (QMetaObject * obj, const char * name) const inline slot
Definition at line 203 of file PythonQtStdDecorators.h.
{ return obj->indexOfProperty(name); }
References PythonQtConvertPairToPython().
indexOfSignal
int PythonQtWrapper_QMetaObject::indexOfSignal (QMetaObject * obj, const char * signal) const inline slot
Definition at line 200 of file PythonQtStdDecorators.h.
{ return obj->indexOfSignal(signal); }
References PythonQtConvertPairToPython().
indexOfSlot
int PythonQtWrapper_QMetaObject::indexOfSlot (QMetaObject * obj, const char * slot) const inline slot
Definition at line 201 of file PythonQtStdDecorators.h.
{ return obj->indexOfSlot(slot); }
References PythonQtConvertPairToPython().
method
QMetaMethod PythonQtWrapper_QMetaObject::method (QMetaObject * obj, int index) const inline slot
Definition at line 207 of file PythonQtStdDecorators.h.
{ return obj->method(index); }
References PythonQtConvertPairToPython().
Referenced by indexOfMethod(), static_QMetaObject_checkConnectArgs(), and static_QMetaObject_normalizedSignature().
methodCount
int PythonQtWrapper_QMetaObject::methodCount (QMetaObject * obj) const inline slot
Definition at line 190 of file PythonQtStdDecorators.h.
{ return obj->methodCount(); }
References PythonQtConvertPairToPython().
methodOffset
int PythonQtWrapper_QMetaObject::methodOffset (QMetaObject * obj) const inline slot
Definition at line 184 of file PythonQtStdDecorators.h.
{ return obj->methodOffset(); }
References PythonQtConvertPairToPython().
property
QMetaProperty PythonQtWrapper_QMetaObject::property (QMetaObject * obj, int index) const inline slot
Definition at line 209 of file PythonQtStdDecorators.h.
{ return obj->property(index); }
References PythonQtConvertPairToPython().
propertyCount
int PythonQtWrapper_QMetaObject::propertyCount (QMetaObject * obj) const inline slot
Definition at line 192 of file PythonQtStdDecorators.h.
{ return obj->propertyCount(); }
References PythonQtConvertPairToPython().
propertyOffset
int PythonQtWrapper_QMetaObject::propertyOffset (QMetaObject * obj) const inline slot
Definition at line 186 of file PythonQtStdDecorators.h.
{ return obj->propertyOffset(); }
References PythonQtConvertPairToPython().
static_QMetaObject_checkConnectArgs
bool PythonQtWrapper_QMetaObject::static_QMetaObject_checkConnectArgs (const char * signal, const char * method) inline slot
Definition at line 213 of file PythonQtStdDecorators.h.
  {
    return QMetaObject::checkConnectArgs(signal, method);
  }
References method(), and PythonQtConvertPairToPython().
static_QMetaObject_normalizedSignature
QByteArray PythonQtWrapper_QMetaObject::static_QMetaObject_normalizedSignature (const char * method) inline slot
Definition at line 217 of file PythonQtStdDecorators.h.
  {
    return QMetaObject::normalizedSignature(method);
  }
References method().
static_QMetaObject_normalizedType
QByteArray PythonQtWrapper_QMetaObject::static_QMetaObject_normalizedType (const char * type) inline slot
Definition at line 221 of file PythonQtStdDecorators.h.
{ return QMetaObject::normalizedType(type); }
superClass
const QMetaObject * PythonQtWrapper_QMetaObject::superClass (QMetaObject * obj) const inline slot
Definition at line 182 of file PythonQtStdDecorators.h.
{ return obj->superClass(); }
References PythonQtConvertPairToPython().
userProperty
QMetaProperty PythonQtWrapper_QMetaObject::userProperty (QMetaObject * obj) const inline slot
Definition at line 211 of file PythonQtStdDecorators.h.
{ return obj->userProperty(); }
References PythonQtConvertPairToPython().
The documentation for this class was generated from the following file:
PythonQtStdDecorators.h