PythonQt: PythonQtSafeObjectPtr Class Reference
PythonQtSafeObjectPtr Class Reference
a smart pointer that stores a PyObject pointer and that handles reference counting automatically
#include <PythonQtObjectPtr.h>
Public Member Functions
PythonQtSafeObjectPtr ()
PythonQtSafeObjectPtr (const PythonQtSafeObjectPtr &p)
PythonQtSafeObjectPtr (const PythonQtObjectPtr &p)
PythonQtSafeObjectPtr (PythonQtSafeObjectPtr &&p) noexcept
rvalue copy constructor, does not need any incref/decref.
PythonQtSafeObjectPtr (PythonQtObjectPtr &&p)
rvalue copy constructor, does not need any incref/decref.
PythonQtSafeObjectPtr (PyObject *o)
~PythonQtSafeObjectPtr ()
PythonQtSafeObjectPtr & operator= (const PythonQtSafeObjectPtr &p)
PythonQtSafeObjectPtr & operator= (const PythonQtObjectPtr &p)
PythonQtSafeObjectPtr & operator= (PythonQtSafeObjectPtr &&p) noexcept
rvalue assignment operator that steals the reference from p
PythonQtSafeObjectPtr & operator= (PythonQtObjectPtr &&p)
rvalue assignment operator that steals the reference from p
PythonQtSafeObjectPtr & operator= (PyObject *o)
bool operator== (const PythonQtSafeObjectPtr &p) const
bool operator!= (const PythonQtSafeObjectPtr &p) const
bool operator== (PyObject *p) const
bool operator!= (PyObject *p) const
bool isNull () const
PyObject * operator-> () const
PyObject & operator* () const
operator PyObject * () const
PyObject * object () const
PyObject * takeObject ()
Protected Member Functions
void setObject (PyObject *o)
void setObjectUnsafe (PyObject *o)
Detailed Description
a smart pointer that stores a PyObject pointer and that handles reference counting automatically
Definition at line 197 of file PythonQtObjectPtr.h.
Constructor & Destructor Documentation
PythonQtSafeObjectPtr() [1/6]
PythonQtSafeObjectPtr::PythonQtSafeObjectPtr () inline
Definition at line 200 of file PythonQtObjectPtr.h.
:_object(nullptr) {}
PythonQtSafeObjectPtr() [2/6]
PythonQtSafeObjectPtr::PythonQtSafeObjectPtr (const PythonQtSafeObjectPtr & p) inline
Definition at line 202 of file PythonQtObjectPtr.h.
    :_object(nullptr) {
    setObject(p.object());
  }
References PythonQtConvertPairToPython().
PythonQtSafeObjectPtr() [3/6]
PythonQtSafeObjectPtr::PythonQtSafeObjectPtr (const PythonQtObjectPtr & p) inline
Definition at line 207 of file PythonQtObjectPtr.h.
    :_object(nullptr) {
    setObject(p.object());
  }
References PythonQtConvertPairToPython().
PythonQtSafeObjectPtr() [4/6]
PythonQtSafeObjectPtr::PythonQtSafeObjectPtr (PythonQtSafeObjectPtr && p) inline noexcept
rvalue copy constructor, does not need any incref/decref.
Definition at line 213 of file PythonQtObjectPtr.h.
    :_object(p._object) {
    p._object = nullptr;
  }
References PythonQtConvertPairToPython().
PythonQtSafeObjectPtr() [5/6]
PythonQtSafeObjectPtr::PythonQtSafeObjectPtr (PythonQtObjectPtr && p) inline
rvalue copy constructor, does not need any incref/decref.
Definition at line 219 of file PythonQtObjectPtr.h.
    :_object(p.takeObject()) {
  }
PythonQtSafeObjectPtr() [6/6]
PythonQtSafeObjectPtr::PythonQtSafeObjectPtr (PyObject * o)
~PythonQtSafeObjectPtr()
PythonQtSafeObjectPtr::~PythonQtSafeObjectPtr ()
Member Function Documentation
isNull()
bool PythonQtSafeObjectPtr::isNull () const inline
Definition at line 277 of file PythonQtObjectPtr.h.
{ return !object(); }
object()
PyObject * PythonQtSafeObjectPtr::object () const inline
Definition at line 285 of file PythonQtObjectPtr.h.
{
    return _object;
  }
operator PyObject *()
PythonQtSafeObjectPtr::operator PyObject * () const inline
Definition at line 283 of file PythonQtObjectPtr.h.
{ return object(); }
operator!=() [1/2]
bool PythonQtSafeObjectPtr::operator!= (const PythonQtSafeObjectPtr & p) const inline
Definition at line 265 of file PythonQtObjectPtr.h.
{
    return !(*this == p);
  }
References PythonQtConvertPairToPython().
operator!=() [2/2]
bool PythonQtSafeObjectPtr::operator!= (PyObject * p) const inline
Definition at line 273 of file PythonQtObjectPtr.h.
{
    return object() != p;
  }
References PythonQtConvertPairToPython().
operator*()
PyObject & PythonQtSafeObjectPtr::operator* () const inline
Definition at line 281 of file PythonQtObjectPtr.h.
{ return *(object()); }
operator->()
PyObject * PythonQtSafeObjectPtr::operator-> () const inline
Definition at line 279 of file PythonQtObjectPtr.h.
{ return object(); }
operator=() [1/5]
PythonQtSafeObjectPtr & PythonQtSafeObjectPtr::operator= (const PythonQtObjectPtr & p) inline
Definition at line 232 of file PythonQtObjectPtr.h.
{
    setObjectUnsafe(p.object());
    return *this;
  }
References PythonQtConvertPairToPython().
operator=() [2/5]
PythonQtSafeObjectPtr & PythonQtSafeObjectPtr::operator= (const PythonQtSafeObjectPtr & p) inline
Definition at line 227 of file PythonQtObjectPtr.h.
{
    setObject(p.object());
    return *this;
  }
References PythonQtConvertPairToPython().
operator=() [3/5]
PythonQtSafeObjectPtr & PythonQtSafeObjectPtr::operator= (PyObject * o) inline
Definition at line 256 of file PythonQtObjectPtr.h.
{
    setObject(o);
    return *this;
  }
References PythonQtConvertPairToPython().
operator=() [4/5]
PythonQtSafeObjectPtr & PythonQtSafeObjectPtr::operator= (PythonQtObjectPtr && p) inline
rvalue assignment operator that steals the reference from p
Definition at line 248 of file PythonQtObjectPtr.h.
{
    if (_object) {
      setObjectUnsafe(nullptr);
    }
    _object = p.takeObject();
    return *this;
  }
References PythonQtConvertPairToPython().
operator=() [5/5]
PythonQtSafeObjectPtr & PythonQtSafeObjectPtr::operator= (PythonQtSafeObjectPtr && p) inline noexcept
rvalue assignment operator that steals the reference from p
Definition at line 238 of file PythonQtObjectPtr.h.
{
    if (_object) {
      setObject(nullptr);
    }
    _object = p._object;
    p._object = nullptr;
    return *this;
  }
References PythonQtConvertPairToPython().
operator==() [1/2]
bool PythonQtSafeObjectPtr::operator== (const PythonQtSafeObjectPtr & p) const inline
Definition at line 261 of file PythonQtObjectPtr.h.
{
    return object() == p.object();
  }
References PythonQtConvertPairToPython().
operator==() [2/2]
bool PythonQtSafeObjectPtr::operator== (PyObject * p) const inline
Definition at line 269 of file PythonQtObjectPtr.h.
{
    return object() == p;
  }
References PythonQtConvertPairToPython().
setObject()
void PythonQtSafeObjectPtr::setObject (PyObject * o) protected
setObjectUnsafe()
void PythonQtSafeObjectPtr::setObjectUnsafe (PyObject * o) protected
takeObject()
PyObject * PythonQtSafeObjectPtr::takeObject () inline
takes the object from the pointer, leaving the pointer empty. the caller has to take care about the decref of the taken object!
Definition at line 291 of file PythonQtObjectPtr.h.
{
    PyObject* o = _object;
    _object = nullptr;
    return o;
  }
References PythonQtConvertPairToPython().
The documentation for this class was generated from the following file:
PythonQtObjectPtr.h