PythonQt: PythonQtStdDecorators Class Reference
PythonQtStdDecorators Class Reference
#include <PythonQtStdDecorators.h>
Public Slots
bool connect (QObject *sender, const QByteArray &signal, PyObject *callable)
bool connect (QObject *sender, const QByteArray &signal, QObject *receiver, const QByteArray &slot, Qt::ConnectionType type=Qt::AutoConnection)
bool connect (QObject *receiver, QObject *sender, const QByteArray &signal, const QByteArray &slot, Qt::ConnectionType type=Qt::AutoConnection)
bool static_QObject_connect (QObject *sender, const QByteArray &signal, PyObject *callable)
bool static_QObject_connect (QObject *sender, const QByteArray &signal, QObject *receiver, const QByteArray &slot, Qt::ConnectionType type=Qt::AutoConnection)
bool disconnect (QObject *sender, const QByteArray &signal, PyObject *callable=nullptr)
bool disconnect (QObject *sender, const QByteArray &signal, QObject *receiver, const QByteArray &slot)
bool static_QObject_disconnect (QObject *sender, const QByteArray &signal, PyObject *callable=nullptr)
bool static_QObject_disconnect (QObject *sender, const QByteArray &signal, QObject *receiver, const QByteArray &slot)
const QMetaObject * metaObject (QObject *obj)
QObject * parent (QObject *o)
void setParent (QObject *o, PythonQtNewOwnerOfThis< QObject * > parent)
const QObjectList * children (QObject *o)
QObject * findChild (QObject *parent, PyObject *type, const QString &name=QString())
QList< QObject * > findChildren (QObject *parent, PyObject *type, const QString &name=QString())
QList< QObject * > findChildren (QObject *parent, PyObject *type, const QRegularExpression &regExp)
bool setProperty (QObject *o, const char *name, const QVariant &value)
QVariant property (QObject *o, const char *name)
double static_Qt_qAbs (double a)
double static_Qt_qBound (double a, double b, double c)
void static_Qt_qDebug (const QByteArray &msg)
void static_Qt_qWarning (const QByteArray &msg)
void static_Qt_qCritical (const QByteArray &msg)
void static_Qt_qFatal (const QByteArray &msg)
bool static_Qt_qFuzzyCompare (double a, double b)
double static_Qt_qMax (double a, double b)
double static_Qt_qMin (double a, double b)
int static_Qt_qRound (double a)
qint64 static_Qt_qRound64 (double a)
const char * static_Qt_qVersion ()
int static_Qt_qrand ()
void static_Qt_qsrand (uint a)
QString tr (QObject *obj, const QString &text, const QString &ambig=QString(), int n=-1)
QString static_Qt_SIGNAL (const QString &s)
QString static_Qt_SLOT (const QString &s)
void static_QTimer_singleShot (int msec, PyObject *callable)
Detailed Description
Definition at line 65 of file PythonQtStdDecorators.h.
Member Function Documentation
children
const QObjectList * PythonQtStdDecorators::children (QObject * o) slot
connect [1/3]
bool PythonQtStdDecorators::connect (QObject * receiver, QObject * sender, const QByteArray & signal, const QByteArray & slot, Qt::ConnectionType type = Qt::AutoConnection) inline slot
Definition at line 72 of file PythonQtStdDecorators.h.
{ return connect(sender, signal, receiver, slot, type); }
References connect(), and PythonQtConvertPairToPython().
Referenced by connect().
connect [2/3]
bool PythonQtStdDecorators::connect (QObject * sender, const QByteArray & signal, PyObject * callable) slot
connect [3/3]
bool PythonQtStdDecorators::connect (QObject * sender, const QByteArray & signal, QObject * receiver, const QByteArray & slot, Qt::ConnectionType type = Qt::AutoConnection) slot
disconnect [1/2]
bool PythonQtStdDecorators::disconnect (QObject * sender, const QByteArray & signal, PyObject * callable = nullptr) slot
disconnect [2/2]
bool PythonQtStdDecorators::disconnect (QObject * sender, const QByteArray & signal, QObject * receiver, const QByteArray & slot) slot
findChild
QObject * PythonQtStdDecorators::findChild (QObject * parent, PyObject * type, const QString & name = QString()) slot
findChildren [1/2]
QList< QObject * > PythonQtStdDecorators::findChildren (QObject * parent, PyObject * type, const QRegularExpression & regExp) slot
findChildren [2/2]
QList< QObject * > PythonQtStdDecorators::findChildren (QObject * parent, PyObject * type, const QString & name = QString()) slot
metaObject
const QMetaObject * PythonQtStdDecorators::metaObject (QObject * obj) slot
parent
QObject * PythonQtStdDecorators::parent (QObject * o) slot
property
QVariant PythonQtStdDecorators::property (QObject * o, const char * name) slot
setParent
void PythonQtStdDecorators::setParent (QObject * o, PythonQtNewOwnerOfThis< QObject * > parent) slot
setProperty
bool PythonQtStdDecorators::setProperty (QObject * o, const char * name, const QVariant & value) slot
static_QObject_connect [1/2]
bool PythonQtStdDecorators::static_QObject_connect (QObject * sender, const QByteArray & signal, PyObject * callable) inline slot
Definition at line 73 of file PythonQtStdDecorators.h.
{ return connect(sender, signal, callable); }
References PythonQtConvertPairToPython().
static_QObject_connect [2/2]
bool PythonQtStdDecorators::static_QObject_connect (QObject * sender, const QByteArray & signal, QObject * receiver, const QByteArray & slot, Qt::ConnectionType type = Qt::AutoConnection) inline slot
Definition at line 74 of file PythonQtStdDecorators.h.
{ return connect(sender, signal, receiver, slot, type); }
References PythonQtConvertPairToPython().
static_QObject_disconnect [1/2]
bool PythonQtStdDecorators::static_QObject_disconnect (QObject * sender, const QByteArray & signal, PyObject * callable = nullptr) inline slot
Definition at line 77 of file PythonQtStdDecorators.h.
{ return disconnect(sender, signal, callable); }
References PythonQtConvertPairToPython().
static_QObject_disconnect [2/2]
bool PythonQtStdDecorators::static_QObject_disconnect (QObject * sender, const QByteArray & signal, QObject * receiver, const QByteArray & slot) inline slot
Definition at line 78 of file PythonQtStdDecorators.h.
{ return disconnect(sender, signal, receiver, slot); }
References PythonQtConvertPairToPython().
static_Qt_qAbs
double PythonQtStdDecorators::static_Qt_qAbs (double a) inline slot
Definition at line 93 of file PythonQtStdDecorators.h.
{ return qAbs(a); }
References PythonQtConvertPairToPython().
static_Qt_qBound
double PythonQtStdDecorators::static_Qt_qBound (double a, double b, double c) inline slot
Definition at line 94 of file PythonQtStdDecorators.h.
{ return qBound(a,b,c); }
References PythonQtConvertPairToPython().
static_Qt_qCritical
void PythonQtStdDecorators::static_Qt_qCritical (const QByteArray & msg) inline slot
Definition at line 99 of file PythonQtStdDecorators.h.
{ qCritical("%s", msg.constData()); }
References PythonQtConvertPairToPython().
static_Qt_qDebug
void PythonQtStdDecorators::static_Qt_qDebug (const QByteArray & msg) inline slot
Definition at line 95 of file PythonQtStdDecorators.h.
{ qDebug("%s", msg.constData()); }
References PythonQtConvertPairToPython().
static_Qt_qFatal
void PythonQtStdDecorators::static_Qt_qFatal (const QByteArray & msg) inline slot
Definition at line 101 of file PythonQtStdDecorators.h.
{ qFatal("%s", msg.constData()); }
References PythonQtConvertPairToPython().
static_Qt_qFuzzyCompare
bool PythonQtStdDecorators::static_Qt_qFuzzyCompare (double a, double b) inline slot
Definition at line 103 of file PythonQtStdDecorators.h.
{ return qFuzzyCompare(a, b); }
References PythonQtConvertPairToPython().
static_Qt_qMax
double PythonQtStdDecorators::static_Qt_qMax (double a, double b) inline slot
Definition at line 104 of file PythonQtStdDecorators.h.
{ return qMax(a, b); }
References PythonQtConvertPairToPython().
static_Qt_qMin
double PythonQtStdDecorators::static_Qt_qMin (double a, double b) inline slot
Definition at line 105 of file PythonQtStdDecorators.h.
{ return qMin(a, b); }
References PythonQtConvertPairToPython().
static_Qt_qrand
int PythonQtStdDecorators::static_Qt_qrand () inline slot
Definition at line 110 of file PythonQtStdDecorators.h.
  {
#if (QT_VERSION < QT_VERSION_CHECK(5, 15, 0))
    return qrand();
#else
    return QRandomGenerator::global()->generate();
#endif
  }
References PythonQtConvertPairToPython().
static_Qt_qRound
int PythonQtStdDecorators::static_Qt_qRound (double a) inline slot
Definition at line 106 of file PythonQtStdDecorators.h.
{ return qRound(a); }
References PythonQtConvertPairToPython().
static_Qt_qRound64
qint64 PythonQtStdDecorators::static_Qt_qRound64 (double a) inline slot
Definition at line 107 of file PythonQtStdDecorators.h.
{ return qRound64(a); }
References PythonQtConvertPairToPython().
static_Qt_qsrand
void PythonQtStdDecorators::static_Qt_qsrand (uint a) inline slot
Definition at line 119 of file PythonQtStdDecorators.h.
  {
#if (QT_VERSION < QT_VERSION_CHECK(5, 15, 0))
    qsrand(a);
#else
    QRandomGenerator::global()->seed(a);
#endif
  }
References PythonQtConvertPairToPython().
static_Qt_qVersion
const char * PythonQtStdDecorators::static_Qt_qVersion () inline slot
Definition at line 108 of file PythonQtStdDecorators.h.
{ return qVersion(); }
References PythonQtConvertPairToPython().
static_Qt_qWarning
void PythonQtStdDecorators::static_Qt_qWarning (const QByteArray & msg) inline slot
Definition at line 97 of file PythonQtStdDecorators.h.
{ qWarning("%s", msg.constData()); }
References PythonQtConvertPairToPython().
static_Qt_SIGNAL
QString PythonQtStdDecorators::static_Qt_SIGNAL (const QString & s) inline slot
Definition at line 130 of file PythonQtStdDecorators.h.
{ return QString("2") + s; }
References PythonQtConvertPairToPython().
static_Qt_SLOT
QString PythonQtStdDecorators::static_Qt_SLOT (const QString & s) inline slot
Definition at line 131 of file PythonQtStdDecorators.h.
{ return QString("1") + s; }
References PythonQtConvertPairToPython().
static_QTimer_singleShot
void PythonQtStdDecorators::static_QTimer_singleShot (int msec, PyObject * callable) slot
tr
QString PythonQtStdDecorators::tr (QObject * obj, const QString & text, const QString & ambig = QString(), int n = -1) slot
The documentation for this class was generated from the following file:
PythonQtStdDecorators.h