PythonQt: PythonQtSlotInfo Class Reference
PythonQtSlotInfo Class Reference
stores information about a slot, including a next pointer to overloaded slots
#include <PythonQtMethodInfo.h>
Public Types
enum Type { MemberSlot , InstanceDecorator , ClassDecorator }
Public Types inherited from PythonQtMethodInfo
enum ParameterType { Unknown = -1 , Variant = -2 }
Public Member Functions
PythonQtSlotInfo (const PythonQtSlotInfo &info)
PythonQtSlotInfo (PythonQtClassInfo *classInfo, const QMetaMethod &meta, int slotIndex, QObject *decorator=nullptr, Type type=MemberSlot)
QList< ParameterInfo > arguments () const
get the parameter infos for the arguments, without return type and instance decorator.
void deleteOverloadsAndThis ()
const QMetaMethod * metaMethod () const
void setUpcastingOffset (int upcastingOffset)
int upcastingOffset () const
int slotIndex () const
get the index of the slot (needed for qt_metacall)
PythonQtSlotInfo * nextInfo () const
get next overloaded slot (which has the same name)
void setNextInfo (PythonQtSlotInfo *next)
set the next overloaded slot
bool isInstanceDecorator () const
returns if the slot is a decorator slot
bool isClassDecorator () const
returns if the slot is a constructor slot
QObject * decorator () const
QString fullSignature (bool skipReturnValue=false, int optionalArgsIndex=-1) const
get the full signature including return type
QByteArray signature () const
get the Qt signature of the slot
QByteArray slotName (bool removeDecorators=false) const
get the short slot name
QStringList overloads (bool skipReturnValue=false) const
QByteArray getImplementingClassName () const
Public Member Functions inherited from PythonQtMethodInfo
PythonQtMethodInfo ()
~PythonQtMethodInfo ()
PythonQtMethodInfo (const QMetaMethod &meta, PythonQtClassInfo *classInfo)
PythonQtMethodInfo (const QByteArray &typeName, const QList< QByteArray > &args)
PythonQtMethodInfo (const PythonQtMethodInfo &other)
int parameterCount () const
returns the number of parameters including the return value
const QList< ParameterInfo > & parameters () const
get the parameter infos
bool shouldAllowThreads () const
Static Public Member Functions
static void invokeQtMethod (QObject *obj, PythonQtSlotInfo *slot, void **argList)
Invoke the given slot on obj, save/restore thread state if needed.
static void setGlobalShouldAllowThreads (bool flag)
Sets if calling slots should release the GIL to allow other Python threads while being inside of C++.
static bool getGlobalShouldAllowThreads ()
Returns if calling slots should release the GIL to allow Python threads while being inside of C++.
Static Public Member Functions inherited from PythonQtMethodInfo
static const PythonQtMethodInfo * getCachedMethodInfo (const QMetaMethod &method, PythonQtClassInfo *classInfo)
static const PythonQtMethodInfo * getCachedMethodInfoFromArgumentList (int numArgs, const char **args)
get the cached method info using the passed in list of return value and arguments, return value needs to be passed as first arg
static void cleanupCachedMethodInfos ()
cleanup the cache
static int nameToType (const char *name)
returns the id for the given type (using an internal dictionary)
static void addParameterTypeAlias (const QByteArray &alias, const QByteArray &name)
add an alias for a typename, e.g. QObjectList and QList<QObject*>.
static void fillParameterInfo (ParameterInfo &type, const QByteArray &name, PythonQtClassInfo *classInfo=nullptr)
fill the parameter info for the given type name
static const ParameterInfo & getParameterInfoForMetaType (int type)
returns a parameter info for the given metatype (and creates and caches one if it is not yet present)
static int getInnerTemplateMetaType (const QByteArray &typeName)
returns the inner type id of a simple template of the form SomeObject<InnerType>
static QByteArray getInnerTemplateTypeName (const QByteArray &typeName)
returns the inner type name of a simple template of the form SomeObject<InnerType>
static QByteArray getInnerListTypeName (const QByteArray &typeName)
returns the inner type name of a simple template or the typename without appended "List".
Additional Inherited Members
Protected Member Functions inherited from PythonQtMethodInfo
void setupAllowThreads ()
Protected Attributes inherited from PythonQtMethodInfo
QList< ParameterInfo > _parameters
bool _shouldAllowThreads
Static Protected Attributes inherited from PythonQtMethodInfo
static QHash< QByteArray, int > _parameterTypeDict
static QHash< QByteArray, QByteArray > _parameterNameAliases
static QHash< QByteArray, PythonQtMethodInfo * > _cachedSignatures
stores the cached signatures of methods to speedup mapping from Qt to Python types
static QHash< int, ParameterInfo > _cachedParameterInfos
Detailed Description
stores information about a slot, including a next pointer to overloaded slots
Definition at line 152 of file PythonQtMethodInfo.h.
Member Enumeration Documentation
Type
enum PythonQtSlotInfo::Type
Enumerator
MemberSlot
InstanceDecorator
ClassDecorator
Definition at line 155 of file PythonQtMethodInfo.h.
            {
    MemberSlot, InstanceDecorator, ClassDecorator
  };
Constructor & Destructor Documentation
PythonQtSlotInfo() [1/2]
PythonQtSlotInfo::PythonQtSlotInfo (const PythonQtSlotInfo & info) inline
Definition at line 159 of file PythonQtMethodInfo.h.
                                                :PythonQtMethodInfo() {
    _meta = info._meta;
    _parameters = info._parameters;
    _shouldAllowThreads = info._shouldAllowThreads;
    _slotIndex = info._slotIndex;
    _next = nullptr;
    _decorator = info._decorator;
    _type = info._type;
    _upcastingOffset = 0;
  }
References PythonQtMethodInfo::_parameters, and PythonQtConvertPairToPython().
PythonQtSlotInfo() [2/2]
PythonQtSlotInfo::PythonQtSlotInfo (PythonQtClassInfo * classInfo, const QMetaMethod & meta, int slotIndex, QObject * decorator = nullptr, Type type = MemberSlot) inline
Definition at line 170 of file PythonQtMethodInfo.h.
                                                                                                                                               :PythonQtMethodInfo()
  {
    const PythonQtMethodInfo* info = getCachedMethodInfo(meta, classInfo);
    _meta = meta;
    _parameters = info->parameters();
    _shouldAllowThreads = info->shouldAllowThreads();
    _slotIndex = slotIndex;
    _next = nullptr;
    _decorator = decorator;
    _type = type;
    _upcastingOffset = 0;
  }
References PythonQtConvertPairToPython().
Member Function Documentation
arguments()
QList< ParameterInfo > PythonQtSlotInfo::arguments () const
get the parameter infos for the arguments, without return type and instance decorator.
decorator()
QObject * PythonQtSlotInfo::decorator () const inline
Definition at line 211 of file PythonQtMethodInfo.h.
{ return _decorator; }
deleteOverloadsAndThis()
void PythonQtSlotInfo::deleteOverloadsAndThis ()
fullSignature()
QString PythonQtSlotInfo::fullSignature (bool skipReturnValue = false, int optionalArgsIndex = -1) const
get the full signature including return type
getGlobalShouldAllowThreads()
static bool PythonQtSlotInfo::getGlobalShouldAllowThreads () static
Returns if calling slots should release the GIL to allow Python threads while being inside of C++.
getImplementingClassName()
QByteArray PythonQtSlotInfo::getImplementingClassName () const
Returns the class name that originally implements this method, regardless where the wrapper is located/implemented.
invokeQtMethod()
static void PythonQtSlotInfo::invokeQtMethod (QObject * obj, PythonQtSlotInfo * slot, void ** argList) static
Invoke the given slot on obj, save/restore thread state if needed.
isClassDecorator()
bool PythonQtSlotInfo::isClassDecorator () const inline
returns if the slot is a constructor slot
Definition at line 209 of file PythonQtMethodInfo.h.
{ return _decorator!=nullptr && _type == ClassDecorator; }
isInstanceDecorator()
bool PythonQtSlotInfo::isInstanceDecorator () const inline
returns if the slot is a decorator slot
Definition at line 206 of file PythonQtMethodInfo.h.
{ return _decorator!=nullptr && _type == InstanceDecorator; }
metaMethod()
const QMetaMethod * PythonQtSlotInfo::metaMethod () const inline
Definition at line 190 of file PythonQtMethodInfo.h.
{ return &_meta; }
nextInfo()
PythonQtSlotInfo * PythonQtSlotInfo::nextInfo () const inline
get next overloaded slot (which has the same name)
Definition at line 200 of file PythonQtMethodInfo.h.
{ return _next; }
overloads()
QStringList PythonQtSlotInfo::overloads (bool skipReturnValue = false) const
gets a list of all overload signatures. Signatures which only differ because of default values are joined using "[]" to indicate the optional arguments.
setGlobalShouldAllowThreads()
static void PythonQtSlotInfo::setGlobalShouldAllowThreads (bool flag) static
Sets if calling slots should release the GIL to allow other Python threads while being inside of C++.
setNextInfo()
void PythonQtSlotInfo::setNextInfo (PythonQtSlotInfo * next) inline
set the next overloaded slot
Definition at line 203 of file PythonQtMethodInfo.h.
{ _next = next; }
References PythonQtConvertPairToPython().
setUpcastingOffset()
void PythonQtSlotInfo::setUpcastingOffset (int upcastingOffset) inline
Definition at line 192 of file PythonQtMethodInfo.h.
{ _upcastingOffset = upcastingOffset; }
signature()
QByteArray PythonQtSlotInfo::signature () const
get the Qt signature of the slot
slotIndex()
int PythonQtSlotInfo::slotIndex () const inline
get the index of the slot (needed for qt_metacall)
Definition at line 197 of file PythonQtMethodInfo.h.
{ return _slotIndex; }
slotName()
QByteArray PythonQtSlotInfo::slotName (bool removeDecorators = false) const
get the short slot name
upcastingOffset()
int PythonQtSlotInfo::upcastingOffset () const inline
Definition at line 194 of file PythonQtMethodInfo.h.
{ return _upcastingOffset; }
The documentation for this class was generated from the following file:
PythonQtMethodInfo.h