PythonQt: PythonQtUtils Namespace Reference
PythonQtUtils Namespace Reference
Functions
QByteArray signature (const QMetaMethod &method)
QByteArray methodName (const QMetaMethod &method)
QByteArray typeName (const QMetaMethod &method)
bool isPythonClassType (PyObject *obj)
Returns of the python object is a class type.
int metaTypeIdFromTypeName (const QByteArray &className)
Returns the meta type ID from a type name.
const char * typeNameFromMetaTypeId (int metaTypeId)
Returns the type name from a meta type ID.
Function Documentation
isPythonClassType()
bool PythonQtUtils::isPythonClassType (PyObject * obj) inline
Returns of the python object is a class type.
Definition at line 87 of file PythonQtUtils.h.
{
#ifdef PY3K
    return PyType_Check(obj);
#else
    // support old-style classes and new style classes
    return (obj->ob_type == &PyClass_Type || obj->ob_type == &PyType_Type);
#endif
  }
References PythonQtConvertPairToPython().
metaTypeIdFromTypeName()
int PythonQtUtils::metaTypeIdFromTypeName (const QByteArray & className) inline
Returns the meta type ID from a type name.
Definition at line 97 of file PythonQtUtils.h.
{
#if QT_VERSION >= QT_VERSION_CHECK(6,0,0)
    return QMetaType::fromName(className.constData()).id();
#else
    return QMetaType::type(className.constData());
#endif
  }
Referenced by PythonQtConvertIntegerMapToPython(), PythonQtConvertPairToPython(), PythonQtConvertPythonToIntegerMap(), and PythonQtConvertPythonToPair().
methodName()
QByteArray PythonQtUtils::methodName (const QMetaMethod & method) inline
Definition at line 62 of file PythonQtUtils.h.
{
#if(QT_VERSION >= QT_VERSION_CHECK(5,0,0))
    return method.name();
#else
    QByteArray sig(method.signature());
    int idx = sig.indexOf('(');
    sig = sig.left(idx);
    return sig;
#endif
  }
References PythonQtConvertPairToPython().
signature()
QByteArray PythonQtUtils::signature (const QMetaMethod & method) inline
Definition at line 54 of file PythonQtUtils.h.
{
#if(QT_VERSION >= QT_VERSION_CHECK(5,0,0))
    return method.methodSignature();
#else
    return QByteArray(method.signature());
#endif
  }
References PythonQtConvertPairToPython().
typeName()
QByteArray PythonQtUtils::typeName (const QMetaMethod & method) inline
Definition at line 73 of file PythonQtUtils.h.
{
#if(QT_VERSION >= QT_VERSION_CHECK(5,0,0))
    QByteArray result = method.typeName();
    if (result == "void") {
      return QByteArray();
    } else {
      return result;
    }
#else
    return method.typeName();
#endif
  }
References PythonQtConvertPairToPython().
typeNameFromMetaTypeId()
const char * PythonQtUtils::typeNameFromMetaTypeId (int metaTypeId) inline
Returns the type name from a meta type ID.
Definition at line 106 of file PythonQtUtils.h.
{
#if QT_VERSION >= QT_VERSION_CHECK(6,0,0)
    return QMetaType(metaTypeId).name();
#else
    return QMetaType::typeName(metaTypeId);
#endif
  }
References PythonQtConvertPairToPython().
Referenced by PythonQtConvertIntegerMapToPython(), PythonQtConvertListOfKnownClassToPythonList(), PythonQtConvertListOfPairToPythonList(), PythonQtConvertListOfValueTypeToPythonList(), PythonQtConvertPairToPython(), PythonQtConvertPythonListToListOfKnownClass(), PythonQtConvertPythonListToListOfPair(), PythonQtConvertPythonListToListOfValueType(), PythonQtConvertPythonToIntegerMap(), and PythonQtConvertPythonToPair().