PythonQt: PythonQtConversion.h File Reference
PythonQtConversion.h File Reference
#include "PythonQtPythonInclude.h"
#include "PythonQt.h"
#include "PythonQtMisc.h"
#include "PythonQtClassInfo.h"
#include "PythonQtMethodInfo.h"
#include <QList>
#include <vector>
Classes
class PythonQtConv
a static class that offers methods for type conversion
Macros
#define PythonQtRegisterListTemplateConverter(type, innertype)
#define PythonQtRegisterListTemplateConverterForKnownClass(type, innertype)
#define PythonQtRegisterQPairConverter(type1, type2)
#define PythonQtRegisterIntegerMapConverter(type, innertype)
#define PythonQtRegisterListTemplateQPairConverter(listtype, type1, type2)
#define PythonQtRegisterToolClassesTemplateConverter(innertype)
#define PythonQtRegisterToolClassesTemplateConverterForKnownClass(innertype)
Typedefs
typedef PyObject * PythonQtConvertMetaTypeToPythonCB(const void *inObject, int metaTypeId)
typedef bool PythonQtConvertPythonToMetaTypeCB(PyObject *inObject, void *outObject, int metaTypeId, bool strict)
typedef QVariant PythonQtConvertPythonSequenceToQVariantListCB(PyObject *inObject)
Functions
template<class ListType , class T >
PyObject * PythonQtConvertListOfValueTypeToPythonList (const void *inList, int metaTypeId)
template<class ListType , class T >
bool PythonQtConvertPythonListToListOfValueType (PyObject *obj, void *outList, int metaTypeId, bool)
template<class ListType , class T >
PyObject * PythonQtConvertListOfKnownClassToPythonList (const void *inList, int metaTypeId)
template<class ListType , class T >
bool PythonQtConvertPythonListToListOfKnownClass (PyObject *obj, void *outList, int metaTypeId, bool)
template<class T1 , class T2 >
PyObject * PythonQtConvertPairToPython (const void *inPair, int metaTypeId)
template<class T1 , class T2 >
bool PythonQtConvertPythonToPair (PyObject *obj, void *outPair, int metaTypeId, bool)
template<class ListType , class T1 , class T2 >
PyObject * PythonQtConvertListOfPairToPythonList (const void *inList, int metaTypeId)
template<class ListType , class T1 , class T2 >
bool PythonQtConvertPythonListToListOfPair (PyObject *obj, void *outList, int metaTypeId, bool)
template<class MapType , class T >
PyObject * PythonQtConvertIntegerMapToPython (const void *inMap, int metaTypeId)
template<class MapType , class T >
bool PythonQtConvertPythonToIntegerMap (PyObject *val, void *outMap, int metaTypeId, bool)
Detailed Description
Author
Florian Link
Last changed by
Author
florian
Date
2006-05
Definition in file PythonQtConversion.h.
Macro Definition Documentation
PythonQtRegisterIntegerMapConverter
#define PythonQtRegisterIntegerMapConverter (type, innertype)
Value:
{ int typeId = qRegisterMetaType<type<int, innertype > >(#type"<int, "#innertype">"); \
  PythonQtConv::registerPythonToMetaTypeConverter(typeId, PythonQtConvertPythonToIntegerMap<type<int, innertype >, innertype>); \
  PythonQtConv::registerMetaTypeToPythonConverter(typeId, PythonQtConvertIntegerMapToPython<type<int, innertype >, innertype>); \
}
Definition at line 76 of file PythonQtConversion.h.
{ int typeId = qRegisterMetaType<type<int, innertype > >(#type"<int, "#innertype">"); \
  PythonQtConv::registerPythonToMetaTypeConverter(typeId, PythonQtConvertPythonToIntegerMap<type<int, innertype >, innertype>); \
  PythonQtConv::registerMetaTypeToPythonConverter(typeId, PythonQtConvertIntegerMapToPython<type<int, innertype >, innertype>); \
}
PythonQtRegisterListTemplateConverter
#define PythonQtRegisterListTemplateConverter (type, innertype)
Value:
{ int typeId = qRegisterMetaType<type<innertype > >(#type"<"#innertype">"); \
PythonQtConv::registerPythonToMetaTypeConverter(typeId, PythonQtConvertPythonListToListOfValueType<type<innertype >, innertype>); \
PythonQtConv::registerMetaTypeToPythonConverter(typeId, PythonQtConvertListOfValueTypeToPythonList<type<innertype >, innertype>); \
}
Definition at line 58 of file PythonQtConversion.h.
{ int typeId = qRegisterMetaType<type<innertype > >(#type"<"#innertype">"); \
PythonQtConv::registerPythonToMetaTypeConverter(typeId, PythonQtConvertPythonListToListOfValueType<type<innertype >, innertype>); \
PythonQtConv::registerMetaTypeToPythonConverter(typeId, PythonQtConvertListOfValueTypeToPythonList<type<innertype >, innertype>); \
}
PythonQtRegisterListTemplateConverterForKnownClass
#define PythonQtRegisterListTemplateConverterForKnownClass (type, innertype)
Value:
{ int typeId = qRegisterMetaType<type<innertype > >(#type"<"#innertype">"); \
  PythonQtConv::registerPythonToMetaTypeConverter(typeId, PythonQtConvertPythonListToListOfKnownClass<type<innertype >, innertype>); \
  PythonQtConv::registerMetaTypeToPythonConverter(typeId, PythonQtConvertListOfKnownClassToPythonList<type<innertype >, innertype>); \
}
Definition at line 64 of file PythonQtConversion.h.
{ int typeId = qRegisterMetaType<type<innertype > >(#type"<"#innertype">"); \
  PythonQtConv::registerPythonToMetaTypeConverter(typeId, PythonQtConvertPythonListToListOfKnownClass<type<innertype >, innertype>); \
  PythonQtConv::registerMetaTypeToPythonConverter(typeId, PythonQtConvertListOfKnownClassToPythonList<type<innertype >, innertype>); \
}
PythonQtRegisterListTemplateQPairConverter
#define PythonQtRegisterListTemplateQPairConverter (listtype, type1, type2)
Value:
{ \
  qRegisterMetaType<QPair<type1, type2> >("QPair<"#type1","#type2">"); \
  int typeId = qRegisterMetaType<listtype<QPair<type1, type2> > >(#listtype"<QPair<"#type1","#type2">>"); \
  PythonQtConv::registerPythonToMetaTypeConverter(typeId, PythonQtConvertPythonListToListOfPair<listtype<QPair<type1, type2> >, type1, type2>); \
  PythonQtConv::registerMetaTypeToPythonConverter(typeId, PythonQtConvertListOfPairToPythonList<listtype<QPair<type1, type2> >, type1, type2>); \
}
Definition at line 82 of file PythonQtConversion.h.
{ \
  qRegisterMetaType<QPair<type1, type2> >("QPair<"#type1","#type2">"); \
  int typeId = qRegisterMetaType<listtype<QPair<type1, type2> > >(#listtype"<QPair<"#type1","#type2">>"); \
  PythonQtConv::registerPythonToMetaTypeConverter(typeId, PythonQtConvertPythonListToListOfPair<listtype<QPair<type1, type2> >, type1, type2>); \
  PythonQtConv::registerMetaTypeToPythonConverter(typeId, PythonQtConvertListOfPairToPythonList<listtype<QPair<type1, type2> >, type1, type2>); \
}
PythonQtRegisterQPairConverter
#define PythonQtRegisterQPairConverter (type1, type2)
Value:
{ int typeId = qRegisterMetaType<QPair<type1, type2> >("QPair<"#type1","#type2">"); \
  PythonQtConv::registerPythonToMetaTypeConverter(typeId, PythonQtConvertPythonToPair<type1, type2>); \
  PythonQtConv::registerMetaTypeToPythonConverter(typeId, PythonQtConvertPairToPython<type1, type2>); \
}
Definition at line 70 of file PythonQtConversion.h.
{ int typeId = qRegisterMetaType<QPair<type1, type2> >("QPair<"#type1","#type2">"); \
  PythonQtConv::registerPythonToMetaTypeConverter(typeId, PythonQtConvertPythonToPair<type1, type2>); \
  PythonQtConv::registerMetaTypeToPythonConverter(typeId, PythonQtConvertPairToPython<type1, type2>); \
}
PythonQtRegisterToolClassesTemplateConverter
#define PythonQtRegisterToolClassesTemplateConverter (innertype)
Value:
  PythonQtRegisterListTemplateConverter(QList, innertype); \
  PythonQtRegisterListTemplateConverter(QVector, innertype); \
  PythonQtRegisterListTemplateConverter(std::vector, innertype);
Definition at line 90 of file PythonQtConversion.h.
PythonQtRegisterToolClassesTemplateConverterForKnownClass
#define PythonQtRegisterToolClassesTemplateConverterForKnownClass (innertype)
Value:
  PythonQtRegisterListTemplateConverterForKnownClass(QList, innertype); \
  PythonQtRegisterListTemplateConverterForKnownClass(QVector, innertype); \
  PythonQtRegisterListTemplateConverterForKnownClass(std::vector, innertype);
Definition at line 95 of file PythonQtConversion.h.
Typedef Documentation
PythonQtConvertMetaTypeToPythonCB
typedef PyObject * PythonQtConvertMetaTypeToPythonCB(const void *inObject, int metaTypeId)
Definition at line 54 of file PythonQtConversion.h.
PythonQtConvertPythonSequenceToQVariantListCB
typedef QVariant PythonQtConvertPythonSequenceToQVariantListCB(PyObject *inObject)
Definition at line 56 of file PythonQtConversion.h.
PythonQtConvertPythonToMetaTypeCB
typedef bool PythonQtConvertPythonToMetaTypeCB(PyObject *inObject, void *outObject, int metaTypeId, bool strict)
Definition at line 55 of file PythonQtConversion.h.
Function Documentation
PythonQtConvertIntegerMapToPython()
template<class MapType , class T > PyObject * PythonQtConvertIntegerMapToPython (const void * inMap, int metaTypeId)
Definition at line 468 of file PythonQtConversion.h.
{
  MapType* map = (MapType*)inMap;
  static int innerType = -1;
  if (innerType == -1) {
    QByteArray innerTypes = PythonQtMethodInfo::getInnerTemplateTypeName(QByteArray(PythonQtUtils::typeNameFromMetaTypeId(metaTypeId)));
    QList<QByteArray> names = innerTypes.split(',');
    innerType = PythonQtUtils::metaTypeIdFromTypeName(names.at(1).trimmed());
  }
  if (innerType == QMetaType::UnknownType) {
    std::cerr << "PythonQtConvertIntegerMapToPython: unknown inner type " << PythonQtUtils::typeNameFromMetaTypeId(metaTypeId) << std::endl;
  }
  PyObject* result = PyDict_New();
  typename MapType::const_iterator t = map->constBegin();
  PyObject* key;
  PyObject* val;
  for (; t != map->constEnd(); t++) {
    key = PyInt_FromLong(t.key());
    val = PythonQtConv::convertQtValueToPythonInternal(innerType, &t.value());
    PyDict_SetItem(result, key, val);
    Py_DECREF(key);
    Py_DECREF(val);
  }
  return result;
}
References PythonQtConv::convertQtValueToPythonInternal(), PythonQtMethodInfo::getInnerTemplateTypeName(), PythonQtUtils::metaTypeIdFromTypeName(), PythonQtConvertPairToPython(), and PythonQtUtils::typeNameFromMetaTypeId().
PythonQtConvertListOfKnownClassToPythonList()
template<class ListType , class T > PyObject * PythonQtConvertListOfKnownClassToPythonList (const void * inList, int metaTypeId)
Definition at line 287 of file PythonQtConversion.h.
{
  ListType* list = (ListType*)inList;
  static PythonQtClassInfo* innerType = PythonQt::priv()->getClassInfo(PythonQtMethodInfo::getInnerListTypeName(QByteArray(PythonQtUtils::typeNameFromMetaTypeId(metaTypeId))));
  if (innerType == nullptr) {
    std::cerr << "PythonQtConvertListOfKnownClassToPythonList: unknown inner type for " << PythonQtUtils::typeNameFromMetaTypeId(metaTypeId) << std::endl;
  }
  PyObject* result = PyTuple_New(list->size());
  int i = 0;
  Q_FOREACH(const T& value, *list) {
    T* newObject = new T(value);
    PythonQtInstanceWrapper* wrap = (PythonQtInstanceWrapper*)PythonQt::priv()->wrapPtr(newObject, innerType->className());
    wrap->_ownedByPythonQt = true;
    PyTuple_SET_ITEM(result, i, (PyObject*)wrap);
    i++;
  }
  return result;
}
References PythonQtInstanceWrapper::_ownedByPythonQt, PythonQtClassInfo::className(), PythonQtPrivate::getClassInfo(), PythonQtMethodInfo::getInnerListTypeName(), PythonQt::priv(), PythonQtUtils::typeNameFromMetaTypeId(), and PythonQtPrivate::wrapPtr().
PythonQtConvertListOfPairToPythonList()
template<class ListType , class T1 , class T2 > PyObject * PythonQtConvertListOfPairToPythonList (const void * inList, int metaTypeId)
Definition at line 416 of file PythonQtConversion.h.
{
  ListType* list = (ListType*)inList;
  static int innerType = PythonQtMethodInfo::getInnerTemplateMetaType(QByteArray(PythonQtUtils::typeNameFromMetaTypeId(metaTypeId)));
  if (innerType == QMetaType::UnknownType) {
    std::cerr << "PythonQtConvertListOfPairToPythonList: unknown inner type " << PythonQtUtils::typeNameFromMetaTypeId(metaTypeId) << std::endl;
  }
  PyObject* result = PyTuple_New(list->size());
  int i = 0;
  typedef const QPair<T1, T2> Pair;
  Q_FOREACH(Pair& value, *list) {
    PyObject* object = PythonQtConvertPairToPython<T1, T2>(&value, innerType);
    PyTuple_SET_ITEM(result, i, object);
    i++;
  }
  return result;
}
References PythonQtMethodInfo::getInnerTemplateMetaType(), PythonQtConvertPairToPython(), and PythonQtUtils::typeNameFromMetaTypeId().
PythonQtConvertListOfValueTypeToPythonList()
template<class ListType , class T > PyObject * PythonQtConvertListOfValueTypeToPythonList (const void * inList, int metaTypeId)
Definition at line 237 of file PythonQtConversion.h.
{
  ListType* list = (ListType*)inList;
  static const int innerType = PythonQtMethodInfo::getInnerTemplateMetaType(QByteArray(PythonQtUtils::typeNameFromMetaTypeId(metaTypeId)));
  if (innerType == QMetaType::UnknownType) {
    std::cerr << "PythonQtConvertListOfValueTypeToPythonList: unknown inner type " << PythonQtUtils::typeNameFromMetaTypeId(metaTypeId) << std::endl;
  }
  PyObject* result = PyTuple_New(list->size());
  int i = 0;
  Q_FOREACH (const T& value, *list) {
    PyTuple_SET_ITEM(result, i, PythonQtConv::convertQtValueToPythonInternal(innerType, &value));
    i++;
  }
  return result;
}
References PythonQtConv::convertQtValueToPythonInternal(), PythonQtMethodInfo::getInnerTemplateMetaType(), and PythonQtUtils::typeNameFromMetaTypeId().
PythonQtConvertPairToPython()
template<class T1 , class T2 > PyObject * PythonQtConvertPairToPython (const void * inPair, int metaTypeId)
Definition at line 347 of file PythonQtConversion.h.
{
  QPair<T1, T2>* pair = (QPair<T1, T2>*)inPair;
  static int innerType1 = -1;
  static int innerType2 = -1;
  if (innerType1==-1) {
    QByteArray innerTypes = PythonQtMethodInfo::getInnerTemplateTypeName(QByteArray(PythonQtUtils::typeNameFromMetaTypeId(metaTypeId)));
    QList<QByteArray> names = innerTypes.split(',');
    innerType1 = PythonQtUtils::metaTypeIdFromTypeName(names.at(0).trimmed());
    innerType2 = PythonQtUtils::metaTypeIdFromTypeName(names.at(1).trimmed());
  }
  if (innerType1 == QMetaType::UnknownType || innerType2 == QMetaType::UnknownType) {
    std::cerr << "PythonQtConvertPairToPython: unknown inner type " << PythonQtUtils::typeNameFromMetaTypeId(metaTypeId) << std::endl;
  }
  PyObject* result = PyTuple_New(2);
  PyTuple_SET_ITEM(result, 0, PythonQtConv::convertQtValueToPythonInternal(innerType1, &pair->first));
  PyTuple_SET_ITEM(result, 1, PythonQtConv::convertQtValueToPythonInternal(innerType2, &pair->second));
  return result;
}
References PythonQtConv::convertQtValueToPythonInternal(), PythonQtMethodInfo::getInnerTemplateTypeName(), PythonQtUtils::metaTypeIdFromTypeName(), and PythonQtUtils::typeNameFromMetaTypeId().
Referenced by PythonQtInstanceWrapper::classInfo(), PythonQtWrapper_QMetaObject::classInfo(), PythonQtWrapper_QMetaObject::classInfoCount(), PythonQtWrapper_QMetaObject::classInfoOffset(), PythonQtStdDecorators::connect(), PythonQtWrapper_QMetaObject::constructor(), PythonQtWrapper_QMetaObject::constructorCount(), PythonQtInstanceWrapper::dynamicClassInfo(), PythonQtWrapper_QMetaObject::enumerator(), PythonQtWrapper_QMetaObject::enumeratorCount(), PythonQtWrapper_QMetaObject::enumeratorOffset(), PythonQtWrapper_QMetaObject::getClassName(), PythonQtWrapper_QMetaObject::indexOfClassInfo(), PythonQtWrapper_QMetaObject::indexOfConstructor(), PythonQtWrapper_QMetaObject::indexOfEnumerator(), PythonQtWrapper_QMetaObject::indexOfMethod(), PythonQtWrapper_QMetaObject::indexOfProperty(), PythonQtWrapper_QMetaObject::indexOfSignal(), PythonQtWrapper_QMetaObject::indexOfSlot(), PythonQtUtils::isPythonClassType(), PythonQtWrapper_QMetaObject::method(), PythonQtWrapper_QMetaObject::methodCount(), PythonQtUtils::methodName(), PythonQtWrapper_QMetaObject::methodOffset(), PythonQtObjectPtr::operator!=(), PythonQtSafeObjectPtr::operator!=(), PythonQtObjectPtr::operator!=(), PythonQtSafeObjectPtr::operator!=(), PythonQtObjectPtr::operator=(), PythonQtSafeObjectPtr::operator=(), PythonQtSafeObjectPtr::operator=(), PythonQtObjectPtr::operator=(), PythonQtObjectPtr::operator=(), PythonQtSafeObjectPtr::operator=(), PythonQtSafeObjectPtr::operator=(), PythonQtObjectPtr::operator=(), PythonQtSafeObjectPtr::operator=(), PythonQtObjectPtr::operator==(), PythonQtSafeObjectPtr::operator==(), PythonQtObjectPtr::operator==(), PythonQtSafeObjectPtr::operator==(), PythonQtInstanceWrapper::passOwnershipToCPP(), PythonQtInstanceWrapper::passOwnershipToPython(), PythonQtWrapper_QMetaObject::property(), PythonQtWrapper_QMetaObject::propertyCount(), PythonQtWrapper_QMetaObject::propertyOffset(), PythonQtConvertIntegerMapToPython(), PythonQtConvertListOfPairToPythonList(), PythonQtConvertPythonListToListOfPair(), PythonQtConvertPythonToIntegerMap(), PythonQtMethodInfo::PythonQtMethodInfo(), PythonQtObjectPtr::PythonQtObjectPtr(), PythonQtObjectPtr::PythonQtObjectPtr(), PythonQtSafeObjectPtr::PythonQtSafeObjectPtr(), PythonQtSafeObjectPtr::PythonQtSafeObjectPtr(), PythonQtSafeObjectPtr::PythonQtSafeObjectPtr(), PythonQtSignalTarget::PythonQtSignalTarget(), PythonQtSlotInfo::PythonQtSlotInfo(), PythonQtSlotInfo::PythonQtSlotInfo(), PythonQtThreadStateSaver::restore(), PythonQtThreadStateSaver::save(), PythonQtSlotInfo::setNextInfo(), PythonQtUtils::signature(), PythonQtWrapper_QMetaObject::static_QMetaObject_checkConnectArgs(), PythonQtStdDecorators::static_QObject_connect(), PythonQtStdDecorators::static_QObject_connect(), PythonQtStdDecorators::static_QObject_disconnect(), PythonQtStdDecorators::static_QObject_disconnect(), PythonQtStdDecorators::static_Qt_qAbs(), PythonQtStdDecorators::static_Qt_qBound(), PythonQtStdDecorators::static_Qt_qCritical(), PythonQtStdDecorators::static_Qt_qDebug(), PythonQtStdDecorators::static_Qt_qFatal(), PythonQtStdDecorators::static_Qt_qFuzzyCompare(), PythonQtStdDecorators::static_Qt_qMax(), PythonQtStdDecorators::static_Qt_qMin(), PythonQtStdDecorators::static_Qt_qrand(), PythonQtStdDecorators::static_Qt_qRound(), PythonQtStdDecorators::static_Qt_qRound64(), PythonQtStdDecorators::static_Qt_qsrand(), PythonQtStdDecorators::static_Qt_qVersion(), PythonQtStdDecorators::static_Qt_qWarning(), PythonQtStdDecorators::static_Qt_SIGNAL(), PythonQtStdDecorators::static_Qt_SLOT(), PythonQtWrapper_QMetaObject::superClass(), PythonQtObjectPtr::takeObject(), PythonQtSafeObjectPtr::takeObject(), PythonQtUtils::typeName(), PythonQtUtils::typeNameFromMetaTypeId(), and PythonQtWrapper_QMetaObject::userProperty().
PythonQtConvertPythonListToListOfKnownClass()
template<class ListType , class T > bool PythonQtConvertPythonListToListOfKnownClass (PyObject * obj, void * outList, int metaTypeId, bool)
Definition at line 307 of file PythonQtConversion.h.
{
  ListType* list = (ListType*)outList;
  static PythonQtClassInfo* innerType = PythonQt::priv()->getClassInfo(PythonQtMethodInfo::getInnerListTypeName(QByteArray(PythonQtUtils::typeNameFromMetaTypeId(metaTypeId))));
  if (innerType == nullptr) {
    std::cerr << "PythonQtConvertListOfKnownClassToPythonList: unknown inner type for " << PythonQtUtils::typeNameFromMetaTypeId(metaTypeId) << std::endl;
  }
  bool result = false;
  if (PySequence_Check(obj)) {
    int count = PySequence_Size(obj);
    if (count >= 0) {
      result = true;
      PyObject* value;
      for (int i = 0; i < count; i++) {
        value = PySequence_GetItem(obj, i);
        if (PyObject_TypeCheck(value, &PythonQtInstanceWrapper_Type)) {
          PythonQtInstanceWrapper* wrap = (PythonQtInstanceWrapper*)value;
          bool ok;
          T* object = (T*)PythonQtConv::castWrapperTo(wrap, innerType->className(), ok);
          Py_XDECREF(value);
          if (ok) {
            list->push_back(*object);
          } else {
            result = false;
            break;
          }
        } else {
          Py_XDECREF(value);
          result = false;
          break;
        }
      }
    }
  }
  return result;
}
References PythonQtConv::castWrapperTo(), PythonQtClassInfo::className(), PythonQtPrivate::getClassInfo(), PythonQtMethodInfo::getInnerListTypeName(), PythonQt::priv(), PythonQtInstanceWrapper_Type, and PythonQtUtils::typeNameFromMetaTypeId().
PythonQtConvertPythonListToListOfPair()
template<class ListType , class T1 , class T2 > bool PythonQtConvertPythonListToListOfPair (PyObject * obj, void * outList, int metaTypeId, bool)
Definition at line 435 of file PythonQtConversion.h.
{
  ListType* list = (ListType*)outList;
  static int innerType = PythonQtMethodInfo::getInnerTemplateMetaType(QByteArray(PythonQtUtils::typeNameFromMetaTypeId(metaTypeId)));
  if (innerType == QMetaType::UnknownType) {
    std::cerr << "PythonQtConvertPythonListToListOfPair: unknown inner type " << PythonQtUtils::typeNameFromMetaTypeId(metaTypeId) << std::endl;
  }
  bool result = false;
  if (PySequence_Check(obj)) {
    int count = PySequence_Size(obj);
    if (count >= 0) {
      result = true;
      PyObject* value;
      for (int i = 0; i < count; i++) {
        QPair<T1, T2> pair;
        value = PySequence_GetItem(obj, i);
        if (PythonQtConvertPythonToPair<T1,T2>(value, &pair, innerType, false)) {
          Py_XDECREF(value);
          list->push_back(pair);
        } else {
          Py_XDECREF(value);
          result = false;
          break;
        }
      }
    }
  }
  return result;
}
References PythonQtMethodInfo::getInnerTemplateMetaType(), PythonQtConvertPairToPython(), and PythonQtUtils::typeNameFromMetaTypeId().
PythonQtConvertPythonListToListOfValueType()
template<class ListType , class T > bool PythonQtConvertPythonListToListOfValueType (PyObject * obj, void * outList, int metaTypeId, bool)
Definition at line 254 of file PythonQtConversion.h.
{
  ListType* list = (ListType*)outList;
  static const int innerType = PythonQtMethodInfo::getInnerTemplateMetaType(QByteArray(PythonQtUtils::typeNameFromMetaTypeId(metaTypeId)));
  if (innerType == QMetaType::UnknownType) {
    std::cerr << "PythonQtConvertPythonListToListOfValueType: unknown inner type " << PythonQtUtils::typeNameFromMetaTypeId(metaTypeId) << std::endl;
  }
  bool result = false;
  if (PySequence_Check(obj)) {
    int count = PySequence_Size(obj);
    if (count >= 0) {
      result = true;
      PyObject* value;
      for (int i = 0;i<count;i++) {
        value = PySequence_GetItem(obj,i);
        // this is quite some overhead, but it avoids having another large switch...
        QVariant v = PythonQtConv::PyObjToQVariant(value, innerType);
        Py_XDECREF(value);
        if (v.isValid()) {
          list->push_back(qvariant_cast<T>(v));
        } else {
          result = false;
          break;
        }
      }
    }
  }
  return result;
}
References PythonQtMethodInfo::getInnerTemplateMetaType(), PythonQtConv::PyObjToQVariant(), and PythonQtUtils::typeNameFromMetaTypeId().
PythonQtConvertPythonToIntegerMap()
template<class MapType , class T > bool PythonQtConvertPythonToIntegerMap (PyObject * val, void * outMap, int metaTypeId, bool)
Definition at line 496 of file PythonQtConversion.h.
{
  MapType* map = (MapType*)outMap;
  static int innerType = -1;
  if (innerType == -1) {
    QByteArray innerTypes = PythonQtMethodInfo::getInnerTemplateTypeName(QByteArray(PythonQtUtils::typeNameFromMetaTypeId(metaTypeId)));
    QList<QByteArray> names = innerTypes.split(',');
    innerType = PythonQtUtils::metaTypeIdFromTypeName(names.at(1).trimmed());
  }
  if (innerType == QMetaType::UnknownType) {
    std::cerr << "PythonQtConvertPythonToIntegerMap: unknown inner type " << PythonQtUtils::typeNameFromMetaTypeId(metaTypeId) << std::endl;
  }
  bool result = false;
  if (PyMapping_Check(val)) {
    result = true;
    PyObject* items = PyMapping_Items(val);
    if (items) {
      int count = PyList_Size(items);
      PyObject* value;
      PyObject* key;
      PyObject* tuple;
      for (int i = 0; i < count; i++) {
        tuple = PyList_GetItem(items, i);
        key = PyTuple_GetItem(tuple, 0);
        value = PyTuple_GetItem(tuple, 1);
        bool ok;
        int intKey = PythonQtConv::PyObjGetInt(key, false, ok);
        // this is quite some overhead, but it avoids having another large switch...
        QVariant v = PythonQtConv::PyObjToQVariant(value, innerType);
        if (v.isValid() && ok) {
          map->insert(intKey, qvariant_cast<T>(v));
        } else {
          result = false;
          break;
        }
      }
      Py_DECREF(items);
    }
  }
  return result;
}
References PythonQtMethodInfo::getInnerTemplateTypeName(), PythonQtUtils::metaTypeIdFromTypeName(), PythonQtConv::PyObjGetInt(), PythonQtConv::PyObjToQVariant(), PythonQtConvertPairToPython(), and PythonQtUtils::typeNameFromMetaTypeId().
PythonQtConvertPythonToPair()
template<class T1 , class T2 > bool PythonQtConvertPythonToPair (PyObject * obj, void * outPair, int metaTypeId, bool)
Definition at line 368 of file PythonQtConversion.h.
{
  QPair<T1, T2>* pair = (QPair<T1, T2>*)outPair;
  static int innerType1 = -1;
  static int innerType2 = -1;
  if (innerType1 == -1) {
    QByteArray innerTypes = PythonQtMethodInfo::getInnerTemplateTypeName(QByteArray(PythonQtUtils::typeNameFromMetaTypeId(metaTypeId)));
    QList<QByteArray> names = innerTypes.split(',');
    innerType1 = PythonQtUtils::metaTypeIdFromTypeName(names.at(0).trimmed());
    innerType2 = PythonQtUtils::metaTypeIdFromTypeName(names.at(1).trimmed());
  }
  if (innerType1 == QMetaType::UnknownType || innerType2 == QMetaType::UnknownType) {
    std::cerr << "PythonQtConvertPythonToPair: unknown inner type " << PythonQtUtils::typeNameFromMetaTypeId(metaTypeId) << std::endl;
  }
  bool result = false;
  if (PySequence_Check(obj)) {
    int count = PySequence_Size(obj);
    if (count == 2) {
      result = true;
      PyObject* value;
      value = PySequence_GetItem(obj, 0);
      // this is quite some overhead, but it avoids having another large switch...
      QVariant v = PythonQtConv::PyObjToQVariant(value, innerType1);
      Py_XDECREF(value);
      if (v.isValid()) {
        pair->first = qvariant_cast<T1>(v);
      } else {
        return false;
      }
      value = PySequence_GetItem(obj, 1);
      // this is quite some overhead, but it avoids having another large switch...
      v = PythonQtConv::PyObjToQVariant(value, innerType2);
      Py_XDECREF(value);
      if (v.isValid()) {
        pair->second = qvariant_cast<T2>(v);
      } else {
        return false;
      }
    }
  }
  return result;
}
References PythonQtMethodInfo::getInnerTemplateTypeName(), PythonQtUtils::metaTypeIdFromTypeName(), PythonQtConv::PyObjToQVariant(), and PythonQtUtils::typeNameFromMetaTypeId().