FROM centos:7

RUN yum update -y
RUN yum groupinstall "Development Tools" -y
RUN yum install -y \
    which \
    python-debug \
    qt5-qtbase-* \
    qt5-qttools* \
    qt5-qtsvg \
    qt5-qtsvg-devel \
    qt5-qtxmlpatterns \
    qt5-qtxmlpatterns-devel \
    qt5-qtmultimedia \
    qt5-qtmultimedia-devel \
    qt5-qt3d \
    qt5-qt3d-devel

RUN mkdir -p work

COPY . work/

WORKDIR work

ARG QT_SELECT=qt5
RUN uname -a; gcc --version | grep "gcc"; python --version; qmake-qt5 --version

CMD ["make"]

# 1. build PythonQt and the generator

RUN qmake-qt5 -r PythonQt.pro \
    PYTHON_VERSION=$(python --version | cut -d " " -f 2 | cut -d "." -f1,2) \
    PYTHON_DIR=$(which python | xargs dirname | xargs dirname)
RUN make

# 2. generate wrappers using the built generator

# workaround to allow to find the Qt include dirs for installed standard qt packages
RUN mkdir /usr/include/qt5ln; ln -s /usr/include/qt5 /usr/include/qt5ln/include

RUN echo "export QTDIR=/usr/include/qt5ln" > generate.sh
RUN echo "cd generator; ./pythonqt_generator" >> generate.sh

CMD ["bash", "generate.sh"]
