FROM gcc:11

RUN apt-get update && apt-get install -y --force-yes \
    python3 \
    python3-dev \
    libpython3-dev \
    qtbase5-dev \
    qtbase5-private-dev \
    qtchooser \
    qt5-qmake \
    qtbase5-dev-tools \
    qttools5-dev \
    qtdeclarative5-dev \
    libqt5svg5* \
    libqt5xmlpatterns5* \
    libqt5multimedia5* \
    libqt5multimediawidgets5* \
    libqt5qml5* \
    libqt5quickwidgets5* \
    qtmultimedia5-dev
RUN apt-get clean

RUN mkdir -p work

COPY . work/

WORKDIR work

ARG QT_SELECT=qt5
RUN uname -a; gcc --version | grep "gcc"; python3 --version; qmake --version

# 1. build PythonQt and the generator

RUN qmake -r PythonQt.pro \
    PYTHON_VERSION=$(python3 --version | cut -d " " -f 2 | cut -d "." -f1,2) \
    PYTHON_DIR=$(which python3 | xargs dirname | xargs dirname)    
RUN make

# 2. generate wrappers using the built generator

# workaround to allow to find the Qt include dirs for installed standard qt packages
RUN mkdir /usr/include/qt5; ln -s /usr/include/x86_64-linux-gnu/qt5 /usr/include/qt5/include

RUN echo "export QTDIR=/usr/include/qt5" > generate.sh
RUN echo "cd generator; ./pythonqt_generator" >> generate.sh

CMD ["bash", "generate.sh"]
