HEADERS += \
           $$PWD/PythonQtWrapper_QAbstractSocket.h \
           $$PWD/PythonQtWrapper_QAuthenticator.h \
           $$PWD/PythonQtWrapper_QFtp.h \
           $$PWD/PythonQtWrapper_QHostAddress.h \
           $$PWD/PythonQtWrapper_QHostInfo.h \
           $$PWD/PythonQtWrapper_QHttp.h \
           $$PWD/PythonQtWrapper_QHttpHeader.h \
           $$PWD/PythonQtWrapper_QHttpRequestHeader.h \
           $$PWD/PythonQtWrapper_QHttpResponseHeader.h \
           $$PWD/PythonQtWrapper_QIPv6Address.h \
           $$PWD/PythonQtWrapper_QLocalServer.h \
           $$PWD/PythonQtWrapper_QLocalSocket.h \
           $$PWD/PythonQtWrapper_QNetworkAccessManager.h \
           $$PWD/PythonQtWrapper_QNetworkAddressEntry.h \
           $$PWD/PythonQtWrapper_QNetworkCookie.h \
           $$PWD/PythonQtWrapper_QNetworkCookieJar.h \
           $$PWD/PythonQtWrapper_QNetworkInterface.h \
           $$PWD/PythonQtWrapper_QNetworkProxy.h \
           $$PWD/PythonQtWrapper_QNetworkReply.h \
           $$PWD/PythonQtWrapper_QNetworkRequest.h \
           $$PWD/PythonQtWrapper_QSsl.h \
           $$PWD/PythonQtWrapper_QTcpServer.h \
           $$PWD/PythonQtWrapper_QTcpSocket.h \
           $$PWD/PythonQtWrapper_QUdpSocket.h \
           $$PWD/PythonQtWrapper_QUrlInfo.h \

SOURCES += \
           $$PWD/PythonQtWrapper_QAbstractSocket.cpp \
           $$PWD/PythonQtWrapper_QAuthenticator.cpp \
           $$PWD/PythonQtWrapper_QFtp.cpp \
           $$PWD/PythonQtWrapper_QHostAddress.cpp \
           $$PWD/PythonQtWrapper_QHostInfo.cpp \
           $$PWD/PythonQtWrapper_QHttp.cpp \
           $$PWD/PythonQtWrapper_QHttpHeader.cpp \
           $$PWD/PythonQtWrapper_QHttpRequestHeader.cpp \
           $$PWD/PythonQtWrapper_QHttpResponseHeader.cpp \
           $$PWD/PythonQtWrapper_QIPv6Address.cpp \
           $$PWD/PythonQtWrapper_QLocalServer.cpp \
           $$PWD/PythonQtWrapper_QLocalSocket.cpp \
           $$PWD/PythonQtWrapper_QNetworkAccessManager.cpp \
           $$PWD/PythonQtWrapper_QNetworkAddressEntry.cpp \
           $$PWD/PythonQtWrapper_QNetworkCookie.cpp \
           $$PWD/PythonQtWrapper_QNetworkCookieJar.cpp \
           $$PWD/PythonQtWrapper_QNetworkInterface.cpp \
           $$PWD/PythonQtWrapper_QNetworkProxy.cpp \
           $$PWD/PythonQtWrapper_QNetworkReply.cpp \
           $$PWD/PythonQtWrapper_QNetworkRequest.cpp \
           $$PWD/PythonQtWrapper_QSsl.cpp \
           $$PWD/PythonQtWrapper_QTcpServer.cpp \
           $$PWD/PythonQtWrapper_QTcpSocket.cpp \
           $$PWD/PythonQtWrapper_QUdpSocket.cpp \
           $$PWD/PythonQtWrapper_QUrlInfo.cpp \
           $$PWD/com_trolltech_qt_network_init.cpp
