HEADERS += \
           $$PWD/PythonQtWrapper_QAbstractButton.h \
           $$PWD/PythonQtWrapper_QAbstractGraphicsShapeItem.h \
           $$PWD/PythonQtWrapper_QAbstractItemDelegate.h \
           $$PWD/PythonQtWrapper_QAbstractItemView.h \
           $$PWD/PythonQtWrapper_QAbstractPageSetupDialog.h \
           $$PWD/PythonQtWrapper_QAbstractPrintDialog.h \
           $$PWD/PythonQtWrapper_QAbstractScrollArea.h \
           $$PWD/PythonQtWrapper_QAbstractSlider.h \
           $$PWD/PythonQtWrapper_QAbstractSpinBox.h \
           $$PWD/PythonQtWrapper_QAccessible.h \
           $$PWD/PythonQtWrapper_QAccessible2Interface.h \
           $$PWD/PythonQtWrapper_QAccessibleBridge.h \
           $$PWD/PythonQtWrapper_QAccessibleEvent.h \
           $$PWD/PythonQtWrapper_QAccessibleInterface.h \
           $$PWD/PythonQtWrapper_QAccessibleInterfaceEx.h \
           $$PWD/PythonQtWrapper_QAccessibleObject.h \
           $$PWD/PythonQtWrapper_QAccessibleObjectEx.h \
           $$PWD/PythonQtWrapper_QAccessiblePlugin.h \
           $$PWD/PythonQtWrapper_QAccessibleTableInterface.h \
           $$PWD/PythonQtWrapper_QAccessibleWidget.h \
           $$PWD/PythonQtWrapper_QAccessibleWidgetEx.h \
           $$PWD/PythonQtWrapper_QAction.h \
           $$PWD/PythonQtWrapper_QActionEvent.h \
           $$PWD/PythonQtWrapper_QActionGroup.h \
           $$PWD/PythonQtWrapper_QApplication.h \
           $$PWD/PythonQtWrapper_QBoxLayout.h \
           $$PWD/PythonQtWrapper_QButtonGroup.h \
           $$PWD/PythonQtWrapper_QCDEStyle.h \
           $$PWD/PythonQtWrapper_QCalendarWidget.h \
           $$PWD/PythonQtWrapper_QCheckBox.h \
           $$PWD/PythonQtWrapper_QCleanlooksStyle.h \
           $$PWD/PythonQtWrapper_QClipboard.h \
           $$PWD/PythonQtWrapper_QClipboardEvent.h \
           $$PWD/PythonQtWrapper_QCloseEvent.h \
           $$PWD/PythonQtWrapper_QColorDialog.h \
           $$PWD/PythonQtWrapper_QColumnView.h \
           $$PWD/PythonQtWrapper_QComboBox.h \
           $$PWD/PythonQtWrapper_QCommandLinkButton.h \
           $$PWD/PythonQtWrapper_QCommonStyle.h \
           $$PWD/PythonQtWrapper_QCompleter.h \
           $$PWD/PythonQtWrapper_QConicalGradient.h \
           $$PWD/PythonQtWrapper_QContextMenuEvent.h \
           $$PWD/PythonQtWrapper_QDataWidgetMapper.h \
           $$PWD/PythonQtWrapper_QDateEdit.h \
           $$PWD/PythonQtWrapper_QDateTimeEdit.h \
           $$PWD/PythonQtWrapper_QDesktopServices.h \
           $$PWD/PythonQtWrapper_QDesktopWidget.h \
           $$PWD/PythonQtWrapper_QDial.h \
           $$PWD/PythonQtWrapper_QDialog.h \
           $$PWD/PythonQtWrapper_QDialogButtonBox.h \
           $$PWD/PythonQtWrapper_QDockWidget.h \
           $$PWD/PythonQtWrapper_QDoubleSpinBox.h \
           $$PWD/PythonQtWrapper_QDoubleValidator.h \
           $$PWD/PythonQtWrapper_QDrag.h \
           $$PWD/PythonQtWrapper_QDragEnterEvent.h \
           $$PWD/PythonQtWrapper_QDragLeaveEvent.h \
           $$PWD/PythonQtWrapper_QDragMoveEvent.h \
           $$PWD/PythonQtWrapper_QDragResponseEvent.h \
           $$PWD/PythonQtWrapper_QDropEvent.h \
           $$PWD/PythonQtWrapper_QErrorMessage.h \
           $$PWD/PythonQtWrapper_QFileDialog.h \
           $$PWD/PythonQtWrapper_QFileIconProvider.h \
           $$PWD/PythonQtWrapper_QFileOpenEvent.h \
           $$PWD/PythonQtWrapper_QFocusEvent.h \
           $$PWD/PythonQtWrapper_QFocusFrame.h \
           $$PWD/PythonQtWrapper_QFontComboBox.h \
           $$PWD/PythonQtWrapper_QFontDialog.h \
           $$PWD/PythonQtWrapper_QFontInfo.h \
           $$PWD/PythonQtWrapper_QFontMetrics.h \
           $$PWD/PythonQtWrapper_QFontMetricsF.h \
           $$PWD/PythonQtWrapper_QFormLayout.h \
           $$PWD/PythonQtWrapper_QFrame.h \
           $$PWD/PythonQtWrapper_QGradient.h \
           $$PWD/PythonQtWrapper_QGraphicsEllipseItem.h \
           $$PWD/PythonQtWrapper_QGraphicsGridLayout.h \
           $$PWD/PythonQtWrapper_QGraphicsItem.h \
           $$PWD/PythonQtWrapper_QGraphicsItemAnimation.h \
           $$PWD/PythonQtWrapper_QGraphicsItemGroup.h \
           $$PWD/PythonQtWrapper_QGraphicsLayout.h \
           $$PWD/PythonQtWrapper_QGraphicsLayoutItem.h \
           $$PWD/PythonQtWrapper_QGraphicsLineItem.h \
           $$PWD/PythonQtWrapper_QGraphicsLinearLayout.h \
           $$PWD/PythonQtWrapper_QGraphicsPathItem.h \
           $$PWD/PythonQtWrapper_QGraphicsPixmapItem.h \
           $$PWD/PythonQtWrapper_QGraphicsPolygonItem.h \
           $$PWD/PythonQtWrapper_QGraphicsProxyWidget.h \
           $$PWD/PythonQtWrapper_QGraphicsRectItem.h \
           $$PWD/PythonQtWrapper_QGraphicsScene.h \
           $$PWD/PythonQtWrapper_QGraphicsSceneContextMenuEvent.h \
           $$PWD/PythonQtWrapper_QGraphicsSceneEvent.h \
           $$PWD/PythonQtWrapper_QGraphicsSceneHelpEvent.h \
           $$PWD/PythonQtWrapper_QGraphicsSceneHoverEvent.h \
           $$PWD/PythonQtWrapper_QGraphicsSceneMouseEvent.h \
           $$PWD/PythonQtWrapper_QGraphicsSceneMoveEvent.h \
           $$PWD/PythonQtWrapper_QGraphicsSceneResizeEvent.h \
           $$PWD/PythonQtWrapper_QGraphicsSceneWheelEvent.h \
           $$PWD/PythonQtWrapper_QGraphicsSimpleTextItem.h \
           $$PWD/PythonQtWrapper_QGraphicsTextItem.h \
           $$PWD/PythonQtWrapper_QGraphicsView.h \
           $$PWD/PythonQtWrapper_QGraphicsWidget.h \
           $$PWD/PythonQtWrapper_QGridLayout.h \
           $$PWD/PythonQtWrapper_QGroupBox.h \
           $$PWD/PythonQtWrapper_QHBoxLayout.h \
           $$PWD/PythonQtWrapper_QHeaderView.h \
           $$PWD/PythonQtWrapper_QHelpEvent.h \
           $$PWD/PythonQtWrapper_QHideEvent.h \
           $$PWD/PythonQtWrapper_QHoverEvent.h \
           $$PWD/PythonQtWrapper_QIconDragEvent.h \
           $$PWD/PythonQtWrapper_QIconEngine.h \
           $$PWD/PythonQtWrapper_QIconEnginePluginV2.h \
           $$PWD/PythonQtWrapper_QImageIOHandler.h \
           $$PWD/PythonQtWrapper_QImageIOPlugin.h \
           $$PWD/PythonQtWrapper_QImageReader.h \
           $$PWD/PythonQtWrapper_QImageWriter.h \
           $$PWD/PythonQtWrapper_QInputContext.h \
           $$PWD/PythonQtWrapper_QInputContextFactory.h \
           $$PWD/PythonQtWrapper_QInputContextPlugin.h \
           $$PWD/PythonQtWrapper_QInputDialog.h \
           $$PWD/PythonQtWrapper_QInputEvent.h \
           $$PWD/PythonQtWrapper_QIntValidator.h \
           $$PWD/PythonQtWrapper_QItemDelegate.h \
           $$PWD/PythonQtWrapper_QItemEditorCreatorBase.h \
           $$PWD/PythonQtWrapper_QItemEditorFactory.h \
           $$PWD/PythonQtWrapper_QItemSelection.h \
           $$PWD/PythonQtWrapper_QItemSelectionModel.h \
           $$PWD/PythonQtWrapper_QItemSelectionRange.h \
           $$PWD/PythonQtWrapper_QKeyEvent.h \
           $$PWD/PythonQtWrapper_QLCDNumber.h \
           $$PWD/PythonQtWrapper_QLabel.h \
           $$PWD/PythonQtWrapper_QLayout.h \
           $$PWD/PythonQtWrapper_QLayoutItem.h \
           $$PWD/PythonQtWrapper_QLineEdit.h \
           $$PWD/PythonQtWrapper_QLinearGradient.h \
           $$PWD/PythonQtWrapper_QListView.h \
           $$PWD/PythonQtWrapper_QListWidget.h \
           $$PWD/PythonQtWrapper_QListWidgetItem.h \
           $$PWD/PythonQtWrapper_QMainWindow.h \
           $$PWD/PythonQtWrapper_QMdiArea.h \
           $$PWD/PythonQtWrapper_QMdiSubWindow.h \
           $$PWD/PythonQtWrapper_QMenu.h \
           $$PWD/PythonQtWrapper_QMenuBar.h \
           $$PWD/PythonQtWrapper_QMessageBox.h \
           $$PWD/PythonQtWrapper_QMotifStyle.h \
           $$PWD/PythonQtWrapper_QMouseEvent.h \
           $$PWD/PythonQtWrapper_QMoveEvent.h \
           $$PWD/PythonQtWrapper_QMovie.h \
           $$PWD/PythonQtWrapper_QPageSetupDialog.h \
           $$PWD/PythonQtWrapper_QPaintDevice.h \
           $$PWD/PythonQtWrapper_QPaintEngine.h \
           $$PWD/PythonQtWrapper_QPaintEngineState.h \
           $$PWD/PythonQtWrapper_QPaintEvent.h \
           $$PWD/PythonQtWrapper_QPainter.h \
           $$PWD/PythonQtWrapper_QPainterPath.h \
           $$PWD/PythonQtWrapper_QPainterPathStroker.h \
           $$PWD/PythonQtWrapper_QPen.h \
           $$PWD/PythonQtWrapper_QPicture.h \
           $$PWD/PythonQtWrapper_QPictureFormatPlugin.h \
           $$PWD/PythonQtWrapper_QPictureIO.h \
           $$PWD/PythonQtWrapper_QPixmapCache.h \
           $$PWD/PythonQtWrapper_QPlainTextDocumentLayout.h \
           $$PWD/PythonQtWrapper_QPlainTextEdit.h \
           $$PWD/PythonQtWrapper_QPlastiqueStyle.h \
           $$PWD/PythonQtWrapper_QPolygonF.h \
           $$PWD/PythonQtWrapper_QPrintDialog.h \
           $$PWD/PythonQtWrapper_QPrintEngine.h \
           $$PWD/PythonQtWrapper_QPrintPreviewDialog.h \
           $$PWD/PythonQtWrapper_QPrintPreviewWidget.h \
           $$PWD/PythonQtWrapper_QPrinter.h \
           $$PWD/PythonQtWrapper_QProgressBar.h \
           $$PWD/PythonQtWrapper_QProgressDialog.h \
           $$PWD/PythonQtWrapper_QPushButton.h \
           $$PWD/PythonQtWrapper_QRadialGradient.h \
           $$PWD/PythonQtWrapper_QRadioButton.h \
           $$PWD/PythonQtWrapper_QReadWriteLock.h \
           $$PWD/PythonQtWrapper_QRegExpValidator.h \
           $$PWD/PythonQtWrapper_QResizeEvent.h \
           $$PWD/PythonQtWrapper_QRubberBand.h \
           $$PWD/PythonQtWrapper_QScrollArea.h \
           $$PWD/PythonQtWrapper_QScrollBar.h \
           $$PWD/PythonQtWrapper_QSessionManager.h \
           $$PWD/PythonQtWrapper_QShortcut.h \
           $$PWD/PythonQtWrapper_QShortcutEvent.h \
           $$PWD/PythonQtWrapper_QShowEvent.h \
           $$PWD/PythonQtWrapper_QSizeGrip.h \
           $$PWD/PythonQtWrapper_QSlider.h \
           $$PWD/PythonQtWrapper_QSound.h \
           $$PWD/PythonQtWrapper_QSpacerItem.h \
           $$PWD/PythonQtWrapper_QSpinBox.h \
           $$PWD/PythonQtWrapper_QSplashScreen.h \
           $$PWD/PythonQtWrapper_QSplitter.h \
           $$PWD/PythonQtWrapper_QSplitterHandle.h \
           $$PWD/PythonQtWrapper_QStackedLayout.h \
           $$PWD/PythonQtWrapper_QStackedWidget.h \
           $$PWD/PythonQtWrapper_QStandardItem.h \
           $$PWD/PythonQtWrapper_QStandardItemModel.h \
           $$PWD/PythonQtWrapper_QStatusBar.h \
           $$PWD/PythonQtWrapper_QStatusTipEvent.h \
           $$PWD/PythonQtWrapper_QStringListModel.h \
           $$PWD/PythonQtWrapper_QStyle.h \
           $$PWD/PythonQtWrapper_QStyleFactory.h \
           $$PWD/PythonQtWrapper_QStyleHintReturn.h \
           $$PWD/PythonQtWrapper_QStyleHintReturnMask.h \
           $$PWD/PythonQtWrapper_QStyleHintReturnVariant.h \
           $$PWD/PythonQtWrapper_QStyleOption.h \
           $$PWD/PythonQtWrapper_QStyleOptionButton.h \
           $$PWD/PythonQtWrapper_QStyleOptionComboBox.h \
           $$PWD/PythonQtWrapper_QStyleOptionDockWidget.h \
           $$PWD/PythonQtWrapper_QStyleOptionDockWidgetV2.h \
           $$PWD/PythonQtWrapper_QStyleOptionFocusRect.h \
           $$PWD/PythonQtWrapper_QStyleOptionFrame.h \
           $$PWD/PythonQtWrapper_QStyleOptionFrameV2.h \
           $$PWD/PythonQtWrapper_QStyleOptionGraphicsItem.h \
           $$PWD/PythonQtWrapper_QStyleOptionGroupBox.h \
           $$PWD/PythonQtWrapper_QStyleOptionHeader.h \
           $$PWD/PythonQtWrapper_QStyleOptionMenuItem.h \
           $$PWD/PythonQtWrapper_QStyleOptionProgressBar.h \
           $$PWD/PythonQtWrapper_QStyleOptionProgressBarV2.h \
           $$PWD/PythonQtWrapper_QStyleOptionRubberBand.h \
           $$PWD/PythonQtWrapper_QStyleOptionSizeGrip.h \
           $$PWD/PythonQtWrapper_QStyleOptionSlider.h \
           $$PWD/PythonQtWrapper_QStyleOptionSpinBox.h \
           $$PWD/PythonQtWrapper_QStyleOptionTab.h \
           $$PWD/PythonQtWrapper_QStyleOptionTabBarBase.h \
           $$PWD/PythonQtWrapper_QStyleOptionTabV2.h \
           $$PWD/PythonQtWrapper_QStyleOptionTabWidgetFrame.h \
           $$PWD/PythonQtWrapper_QStyleOptionTitleBar.h \
           $$PWD/PythonQtWrapper_QStyleOptionToolBar.h \
           $$PWD/PythonQtWrapper_QStyleOptionToolBox.h \
           $$PWD/PythonQtWrapper_QStyleOptionToolBoxV2.h \
           $$PWD/PythonQtWrapper_QStyleOptionToolButton.h \
           $$PWD/PythonQtWrapper_QStyleOptionViewItem.h \
           $$PWD/PythonQtWrapper_QStyleOptionViewItemV2.h \
           $$PWD/PythonQtWrapper_QStyleOptionViewItemV3.h \
           $$PWD/PythonQtWrapper_QStyleOptionViewItemV4.h \
           $$PWD/PythonQtWrapper_QStylePainter.h \
           $$PWD/PythonQtWrapper_QStylePlugin.h \
           $$PWD/PythonQtWrapper_QStyledItemDelegate.h \
           $$PWD/PythonQtWrapper_QSyntaxHighlighter.h \
           $$PWD/PythonQtWrapper_QSystemTrayIcon.h \
           $$PWD/PythonQtWrapper_QTabBar.h \
           $$PWD/PythonQtWrapper_QTabWidget.h \
           $$PWD/PythonQtWrapper_QTableView.h \
           $$PWD/PythonQtWrapper_QTableWidget.h \
           $$PWD/PythonQtWrapper_QTableWidgetItem.h \
           $$PWD/PythonQtWrapper_QTableWidgetSelectionRange.h \
           $$PWD/PythonQtWrapper_QTabletEvent.h \
           $$PWD/PythonQtWrapper_QTextBlock.h \
           $$PWD/PythonQtWrapper_QTextBlockFormat.h \
           $$PWD/PythonQtWrapper_QTextBlockGroup.h \
           $$PWD/PythonQtWrapper_QTextBlockUserData.h \
           $$PWD/PythonQtWrapper_QTextBrowser.h \
           $$PWD/PythonQtWrapper_QTextCharFormat.h \
           $$PWD/PythonQtWrapper_QTextCursor.h \
           $$PWD/PythonQtWrapper_QTextDocument.h \
           $$PWD/PythonQtWrapper_QTextDocumentFragment.h \
           $$PWD/PythonQtWrapper_QTextEdit.h \
           $$PWD/PythonQtWrapper_QTextFragment.h \
           $$PWD/PythonQtWrapper_QTextFrame.h \
           $$PWD/PythonQtWrapper_QTextFrameFormat.h \
           $$PWD/PythonQtWrapper_QTextImageFormat.h \
           $$PWD/PythonQtWrapper_QTextInlineObject.h \
           $$PWD/PythonQtWrapper_QTextItem.h \
           $$PWD/PythonQtWrapper_QTextLine.h \
           $$PWD/PythonQtWrapper_QTextList.h \
           $$PWD/PythonQtWrapper_QTextListFormat.h \
           $$PWD/PythonQtWrapper_QTextObject.h \
           $$PWD/PythonQtWrapper_QTextObjectInterface.h \
           $$PWD/PythonQtWrapper_QTextTable.h \
           $$PWD/PythonQtWrapper_QTextTableCell.h \
           $$PWD/PythonQtWrapper_QTextTableCellFormat.h \
           $$PWD/PythonQtWrapper_QTextTableFormat.h \
           $$PWD/PythonQtWrapper_QTimeEdit.h \
           $$PWD/PythonQtWrapper_QToolBar.h \
           $$PWD/PythonQtWrapper_QToolBarChangeEvent.h \
           $$PWD/PythonQtWrapper_QToolBox.h \
           $$PWD/PythonQtWrapper_QToolButton.h \
           $$PWD/PythonQtWrapper_QToolTip.h \
           $$PWD/PythonQtWrapper_QTransform.h \
           $$PWD/PythonQtWrapper_QTreeView.h \
           $$PWD/PythonQtWrapper_QTreeWidget.h \
           $$PWD/PythonQtWrapper_QTreeWidgetItem.h \
           $$PWD/PythonQtWrapper_QUndoCommand.h \
           $$PWD/PythonQtWrapper_QUndoGroup.h \
           $$PWD/PythonQtWrapper_QUndoStack.h \
           $$PWD/PythonQtWrapper_QUndoView.h \
           $$PWD/PythonQtWrapper_QVBoxLayout.h \
           $$PWD/PythonQtWrapper_QValidator.h \
           $$PWD/PythonQtWrapper_QWhatsThis.h \
           $$PWD/PythonQtWrapper_QWhatsThisClickedEvent.h \
           $$PWD/PythonQtWrapper_QWheelEvent.h \
           $$PWD/PythonQtWrapper_QWidget.h \
           $$PWD/PythonQtWrapper_QWidgetAction.h \
           $$PWD/PythonQtWrapper_QWidgetItem.h \
           $$PWD/PythonQtWrapper_QWindowStateChangeEvent.h \
           $$PWD/PythonQtWrapper_QWindowsStyle.h \
           $$PWD/PythonQtWrapper_QWizard.h \
           $$PWD/PythonQtWrapper_QWizardPage.h \
           $$PWD/PythonQtWrapper_QWorkspace.h \

SOURCES += \
           $$PWD/PythonQtWrapper_QAbstractButton.cpp \
           $$PWD/PythonQtWrapper_QAbstractGraphicsShapeItem.cpp \
           $$PWD/PythonQtWrapper_QAbstractItemDelegate.cpp \
           $$PWD/PythonQtWrapper_QAbstractItemView.cpp \
           $$PWD/PythonQtWrapper_QAbstractPageSetupDialog.cpp \
           $$PWD/PythonQtWrapper_QAbstractPrintDialog.cpp \
           $$PWD/PythonQtWrapper_QAbstractScrollArea.cpp \
           $$PWD/PythonQtWrapper_QAbstractSlider.cpp \
           $$PWD/PythonQtWrapper_QAbstractSpinBox.cpp \
           $$PWD/PythonQtWrapper_QAccessible.cpp \
           $$PWD/PythonQtWrapper_QAccessible2Interface.cpp \
           $$PWD/PythonQtWrapper_QAccessibleBridge.cpp \
           $$PWD/PythonQtWrapper_QAccessibleEvent.cpp \
           $$PWD/PythonQtWrapper_QAccessibleInterface.cpp \
           $$PWD/PythonQtWrapper_QAccessibleInterfaceEx.cpp \
           $$PWD/PythonQtWrapper_QAccessibleObject.cpp \
           $$PWD/PythonQtWrapper_QAccessibleObjectEx.cpp \
           $$PWD/PythonQtWrapper_QAccessiblePlugin.cpp \
           $$PWD/PythonQtWrapper_QAccessibleTableInterface.cpp \
           $$PWD/PythonQtWrapper_QAccessibleWidget.cpp \
           $$PWD/PythonQtWrapper_QAccessibleWidgetEx.cpp \
           $$PWD/PythonQtWrapper_QAction.cpp \
           $$PWD/PythonQtWrapper_QActionEvent.cpp \
           $$PWD/PythonQtWrapper_QActionGroup.cpp \
           $$PWD/PythonQtWrapper_QApplication.cpp \
           $$PWD/PythonQtWrapper_QBoxLayout.cpp \
           $$PWD/PythonQtWrapper_QButtonGroup.cpp \
           $$PWD/PythonQtWrapper_QCDEStyle.cpp \
           $$PWD/PythonQtWrapper_QCalendarWidget.cpp \
           $$PWD/PythonQtWrapper_QCheckBox.cpp \
           $$PWD/PythonQtWrapper_QCleanlooksStyle.cpp \
           $$PWD/PythonQtWrapper_QClipboard.cpp \
           $$PWD/PythonQtWrapper_QClipboardEvent.cpp \
           $$PWD/PythonQtWrapper_QCloseEvent.cpp \
           $$PWD/PythonQtWrapper_QColorDialog.cpp \
           $$PWD/PythonQtWrapper_QColumnView.cpp \
           $$PWD/PythonQtWrapper_QComboBox.cpp \
           $$PWD/PythonQtWrapper_QCommandLinkButton.cpp \
           $$PWD/PythonQtWrapper_QCommonStyle.cpp \
           $$PWD/PythonQtWrapper_QCompleter.cpp \
           $$PWD/PythonQtWrapper_QConicalGradient.cpp \
           $$PWD/PythonQtWrapper_QContextMenuEvent.cpp \
           $$PWD/PythonQtWrapper_QDataWidgetMapper.cpp \
           $$PWD/PythonQtWrapper_QDateEdit.cpp \
           $$PWD/PythonQtWrapper_QDateTimeEdit.cpp \
           $$PWD/PythonQtWrapper_QDesktopServices.cpp \
           $$PWD/PythonQtWrapper_QDesktopWidget.cpp \
           $$PWD/PythonQtWrapper_QDial.cpp \
           $$PWD/PythonQtWrapper_QDialog.cpp \
           $$PWD/PythonQtWrapper_QDialogButtonBox.cpp \
           $$PWD/PythonQtWrapper_QDockWidget.cpp \
           $$PWD/PythonQtWrapper_QDoubleSpinBox.cpp \
           $$PWD/PythonQtWrapper_QDoubleValidator.cpp \
           $$PWD/PythonQtWrapper_QDrag.cpp \
           $$PWD/PythonQtWrapper_QDragEnterEvent.cpp \
           $$PWD/PythonQtWrapper_QDragLeaveEvent.cpp \
           $$PWD/PythonQtWrapper_QDragMoveEvent.cpp \
           $$PWD/PythonQtWrapper_QDragResponseEvent.cpp \
           $$PWD/PythonQtWrapper_QDropEvent.cpp \
           $$PWD/PythonQtWrapper_QErrorMessage.cpp \
           $$PWD/PythonQtWrapper_QFileDialog.cpp \
           $$PWD/PythonQtWrapper_QFileIconProvider.cpp \
           $$PWD/PythonQtWrapper_QFileOpenEvent.cpp \
           $$PWD/PythonQtWrapper_QFocusEvent.cpp \
           $$PWD/PythonQtWrapper_QFocusFrame.cpp \
           $$PWD/PythonQtWrapper_QFontComboBox.cpp \
           $$PWD/PythonQtWrapper_QFontDialog.cpp \
           $$PWD/PythonQtWrapper_QFontInfo.cpp \
           $$PWD/PythonQtWrapper_QFontMetrics.cpp \
           $$PWD/PythonQtWrapper_QFontMetricsF.cpp \
           $$PWD/PythonQtWrapper_QFormLayout.cpp \
           $$PWD/PythonQtWrapper_QFrame.cpp \
           $$PWD/PythonQtWrapper_QGradient.cpp \
           $$PWD/PythonQtWrapper_QGraphicsEllipseItem.cpp \
           $$PWD/PythonQtWrapper_QGraphicsGridLayout.cpp \
           $$PWD/PythonQtWrapper_QGraphicsItem.cpp \
           $$PWD/PythonQtWrapper_QGraphicsItemAnimation.cpp \
           $$PWD/PythonQtWrapper_QGraphicsItemGroup.cpp \
           $$PWD/PythonQtWrapper_QGraphicsLayout.cpp \
           $$PWD/PythonQtWrapper_QGraphicsLayoutItem.cpp \
           $$PWD/PythonQtWrapper_QGraphicsLineItem.cpp \
           $$PWD/PythonQtWrapper_QGraphicsLinearLayout.cpp \
           $$PWD/PythonQtWrapper_QGraphicsPathItem.cpp \
           $$PWD/PythonQtWrapper_QGraphicsPixmapItem.cpp \
           $$PWD/PythonQtWrapper_QGraphicsPolygonItem.cpp \
           $$PWD/PythonQtWrapper_QGraphicsProxyWidget.cpp \
           $$PWD/PythonQtWrapper_QGraphicsRectItem.cpp \
           $$PWD/PythonQtWrapper_QGraphicsScene.cpp \
           $$PWD/PythonQtWrapper_QGraphicsSceneContextMenuEvent.cpp \
           $$PWD/PythonQtWrapper_QGraphicsSceneEvent.cpp \
           $$PWD/PythonQtWrapper_QGraphicsSceneHelpEvent.cpp \
           $$PWD/PythonQtWrapper_QGraphicsSceneHoverEvent.cpp \
           $$PWD/PythonQtWrapper_QGraphicsSceneMouseEvent.cpp \
           $$PWD/PythonQtWrapper_QGraphicsSceneMoveEvent.cpp \
           $$PWD/PythonQtWrapper_QGraphicsSceneResizeEvent.cpp \
           $$PWD/PythonQtWrapper_QGraphicsSceneWheelEvent.cpp \
           $$PWD/PythonQtWrapper_QGraphicsSimpleTextItem.cpp \
           $$PWD/PythonQtWrapper_QGraphicsTextItem.cpp \
           $$PWD/PythonQtWrapper_QGraphicsView.cpp \
           $$PWD/PythonQtWrapper_QGraphicsWidget.cpp \
           $$PWD/PythonQtWrapper_QGridLayout.cpp \
           $$PWD/PythonQtWrapper_QGroupBox.cpp \
           $$PWD/PythonQtWrapper_QHBoxLayout.cpp \
           $$PWD/PythonQtWrapper_QHeaderView.cpp \
           $$PWD/PythonQtWrapper_QHelpEvent.cpp \
           $$PWD/PythonQtWrapper_QHideEvent.cpp \
           $$PWD/PythonQtWrapper_QHoverEvent.cpp \
           $$PWD/PythonQtWrapper_QIconDragEvent.cpp \
           $$PWD/PythonQtWrapper_QIconEngine.cpp \
           $$PWD/PythonQtWrapper_QIconEnginePluginV2.cpp \
           $$PWD/PythonQtWrapper_QImageIOHandler.cpp \
           $$PWD/PythonQtWrapper_QImageIOPlugin.cpp \
           $$PWD/PythonQtWrapper_QImageReader.cpp \
           $$PWD/PythonQtWrapper_QImageWriter.cpp \
           $$PWD/PythonQtWrapper_QInputContext.cpp \
           $$PWD/PythonQtWrapper_QInputContextFactory.cpp \
           $$PWD/PythonQtWrapper_QInputContextPlugin.cpp \
           $$PWD/PythonQtWrapper_QInputDialog.cpp \
           $$PWD/PythonQtWrapper_QInputEvent.cpp \
           $$PWD/PythonQtWrapper_QIntValidator.cpp \
           $$PWD/PythonQtWrapper_QItemDelegate.cpp \
           $$PWD/PythonQtWrapper_QItemEditorCreatorBase.cpp \
           $$PWD/PythonQtWrapper_QItemEditorFactory.cpp \
           $$PWD/PythonQtWrapper_QItemSelection.cpp \
           $$PWD/PythonQtWrapper_QItemSelectionModel.cpp \
           $$PWD/PythonQtWrapper_QItemSelectionRange.cpp \
           $$PWD/PythonQtWrapper_QKeyEvent.cpp \
           $$PWD/PythonQtWrapper_QLCDNumber.cpp \
           $$PWD/PythonQtWrapper_QLabel.cpp \
           $$PWD/PythonQtWrapper_QLayout.cpp \
           $$PWD/PythonQtWrapper_QLayoutItem.cpp \
           $$PWD/PythonQtWrapper_QLineEdit.cpp \
           $$PWD/PythonQtWrapper_QLinearGradient.cpp \
           $$PWD/PythonQtWrapper_QListView.cpp \
           $$PWD/PythonQtWrapper_QListWidget.cpp \
           $$PWD/PythonQtWrapper_QListWidgetItem.cpp \
           $$PWD/PythonQtWrapper_QMainWindow.cpp \
           $$PWD/PythonQtWrapper_QMdiArea.cpp \
           $$PWD/PythonQtWrapper_QMdiSubWindow.cpp \
           $$PWD/PythonQtWrapper_QMenu.cpp \
           $$PWD/PythonQtWrapper_QMenuBar.cpp \
           $$PWD/PythonQtWrapper_QMessageBox.cpp \
           $$PWD/PythonQtWrapper_QMotifStyle.cpp \
           $$PWD/PythonQtWrapper_QMouseEvent.cpp \
           $$PWD/PythonQtWrapper_QMoveEvent.cpp \
           $$PWD/PythonQtWrapper_QMovie.cpp \
           $$PWD/PythonQtWrapper_QPageSetupDialog.cpp \
           $$PWD/PythonQtWrapper_QPaintDevice.cpp \
           $$PWD/PythonQtWrapper_QPaintEngine.cpp \
           $$PWD/PythonQtWrapper_QPaintEngineState.cpp \
           $$PWD/PythonQtWrapper_QPaintEvent.cpp \
           $$PWD/PythonQtWrapper_QPainter.cpp \
           $$PWD/PythonQtWrapper_QPainterPath.cpp \
           $$PWD/PythonQtWrapper_QPainterPathStroker.cpp \
           $$PWD/PythonQtWrapper_QPen.cpp \
           $$PWD/PythonQtWrapper_QPicture.cpp \
           $$PWD/PythonQtWrapper_QPictureFormatPlugin.cpp \
           $$PWD/PythonQtWrapper_QPictureIO.cpp \
           $$PWD/PythonQtWrapper_QPixmapCache.cpp \
           $$PWD/PythonQtWrapper_QPlainTextDocumentLayout.cpp \
           $$PWD/PythonQtWrapper_QPlainTextEdit.cpp \
           $$PWD/PythonQtWrapper_QPlastiqueStyle.cpp \
           $$PWD/PythonQtWrapper_QPolygonF.cpp \
           $$PWD/PythonQtWrapper_QPrintDialog.cpp \
           $$PWD/PythonQtWrapper_QPrintEngine.cpp \
           $$PWD/PythonQtWrapper_QPrintPreviewDialog.cpp \
           $$PWD/PythonQtWrapper_QPrintPreviewWidget.cpp \
           $$PWD/PythonQtWrapper_QPrinter.cpp \
           $$PWD/PythonQtWrapper_QProgressBar.cpp \
           $$PWD/PythonQtWrapper_QProgressDialog.cpp \
           $$PWD/PythonQtWrapper_QPushButton.cpp \
           $$PWD/PythonQtWrapper_QRadialGradient.cpp \
           $$PWD/PythonQtWrapper_QRadioButton.cpp \
           $$PWD/PythonQtWrapper_QReadWriteLock.cpp \
           $$PWD/PythonQtWrapper_QRegExpValidator.cpp \
           $$PWD/PythonQtWrapper_QResizeEvent.cpp \
           $$PWD/PythonQtWrapper_QRubberBand.cpp \
           $$PWD/PythonQtWrapper_QScrollArea.cpp \
           $$PWD/PythonQtWrapper_QScrollBar.cpp \
           $$PWD/PythonQtWrapper_QSessionManager.cpp \
           $$PWD/PythonQtWrapper_QShortcut.cpp \
           $$PWD/PythonQtWrapper_QShortcutEvent.cpp \
           $$PWD/PythonQtWrapper_QShowEvent.cpp \
           $$PWD/PythonQtWrapper_QSizeGrip.cpp \
           $$PWD/PythonQtWrapper_QSlider.cpp \
           $$PWD/PythonQtWrapper_QSound.cpp \
           $$PWD/PythonQtWrapper_QSpacerItem.cpp \
           $$PWD/PythonQtWrapper_QSpinBox.cpp \
           $$PWD/PythonQtWrapper_QSplashScreen.cpp \
           $$PWD/PythonQtWrapper_QSplitter.cpp \
           $$PWD/PythonQtWrapper_QSplitterHandle.cpp \
           $$PWD/PythonQtWrapper_QStackedLayout.cpp \
           $$PWD/PythonQtWrapper_QStackedWidget.cpp \
           $$PWD/PythonQtWrapper_QStandardItem.cpp \
           $$PWD/PythonQtWrapper_QStandardItemModel.cpp \
           $$PWD/PythonQtWrapper_QStatusBar.cpp \
           $$PWD/PythonQtWrapper_QStatusTipEvent.cpp \
           $$PWD/PythonQtWrapper_QStringListModel.cpp \
           $$PWD/PythonQtWrapper_QStyle.cpp \
           $$PWD/PythonQtWrapper_QStyleFactory.cpp \
           $$PWD/PythonQtWrapper_QStyleHintReturn.cpp \
           $$PWD/PythonQtWrapper_QStyleHintReturnMask.cpp \
           $$PWD/PythonQtWrapper_QStyleHintReturnVariant.cpp \
           $$PWD/PythonQtWrapper_QStyleOption.cpp \
           $$PWD/PythonQtWrapper_QStyleOptionButton.cpp \
           $$PWD/PythonQtWrapper_QStyleOptionComboBox.cpp \
           $$PWD/PythonQtWrapper_QStyleOptionDockWidget.cpp \
           $$PWD/PythonQtWrapper_QStyleOptionDockWidgetV2.cpp \
           $$PWD/PythonQtWrapper_QStyleOptionFocusRect.cpp \
           $$PWD/PythonQtWrapper_QStyleOptionFrame.cpp \
           $$PWD/PythonQtWrapper_QStyleOptionFrameV2.cpp \
           $$PWD/PythonQtWrapper_QStyleOptionGraphicsItem.cpp \
           $$PWD/PythonQtWrapper_QStyleOptionGroupBox.cpp \
           $$PWD/PythonQtWrapper_QStyleOptionHeader.cpp \
           $$PWD/PythonQtWrapper_QStyleOptionMenuItem.cpp \
           $$PWD/PythonQtWrapper_QStyleOptionProgressBar.cpp \
           $$PWD/PythonQtWrapper_QStyleOptionProgressBarV2.cpp \
           $$PWD/PythonQtWrapper_QStyleOptionRubberBand.cpp \
           $$PWD/PythonQtWrapper_QStyleOptionSizeGrip.cpp \
           $$PWD/PythonQtWrapper_QStyleOptionSlider.cpp \
           $$PWD/PythonQtWrapper_QStyleOptionSpinBox.cpp \
           $$PWD/PythonQtWrapper_QStyleOptionTab.cpp \
           $$PWD/PythonQtWrapper_QStyleOptionTabBarBase.cpp \
           $$PWD/PythonQtWrapper_QStyleOptionTabV2.cpp \
           $$PWD/PythonQtWrapper_QStyleOptionTabWidgetFrame.cpp \
           $$PWD/PythonQtWrapper_QStyleOptionTitleBar.cpp \
           $$PWD/PythonQtWrapper_QStyleOptionToolBar.cpp \
           $$PWD/PythonQtWrapper_QStyleOptionToolBox.cpp \
           $$PWD/PythonQtWrapper_QStyleOptionToolBoxV2.cpp \
           $$PWD/PythonQtWrapper_QStyleOptionToolButton.cpp \
           $$PWD/PythonQtWrapper_QStyleOptionViewItem.cpp \
           $$PWD/PythonQtWrapper_QStyleOptionViewItemV2.cpp \
           $$PWD/PythonQtWrapper_QStyleOptionViewItemV3.cpp \
           $$PWD/PythonQtWrapper_QStyleOptionViewItemV4.cpp \
           $$PWD/PythonQtWrapper_QStylePainter.cpp \
           $$PWD/PythonQtWrapper_QStylePlugin.cpp \
           $$PWD/PythonQtWrapper_QStyledItemDelegate.cpp \
           $$PWD/PythonQtWrapper_QSyntaxHighlighter.cpp \
           $$PWD/PythonQtWrapper_QSystemTrayIcon.cpp \
           $$PWD/PythonQtWrapper_QTabBar.cpp \
           $$PWD/PythonQtWrapper_QTabWidget.cpp \
           $$PWD/PythonQtWrapper_QTableView.cpp \
           $$PWD/PythonQtWrapper_QTableWidget.cpp \
           $$PWD/PythonQtWrapper_QTableWidgetItem.cpp \
           $$PWD/PythonQtWrapper_QTableWidgetSelectionRange.cpp \
           $$PWD/PythonQtWrapper_QTabletEvent.cpp \
           $$PWD/PythonQtWrapper_QTextBlock.cpp \
           $$PWD/PythonQtWrapper_QTextBlockFormat.cpp \
           $$PWD/PythonQtWrapper_QTextBlockGroup.cpp \
           $$PWD/PythonQtWrapper_QTextBlockUserData.cpp \
           $$PWD/PythonQtWrapper_QTextBrowser.cpp \
           $$PWD/PythonQtWrapper_QTextCharFormat.cpp \
           $$PWD/PythonQtWrapper_QTextCursor.cpp \
           $$PWD/PythonQtWrapper_QTextDocument.cpp \
           $$PWD/PythonQtWrapper_QTextDocumentFragment.cpp \
           $$PWD/PythonQtWrapper_QTextEdit.cpp \
           $$PWD/PythonQtWrapper_QTextFragment.cpp \
           $$PWD/PythonQtWrapper_QTextFrame.cpp \
           $$PWD/PythonQtWrapper_QTextFrameFormat.cpp \
           $$PWD/PythonQtWrapper_QTextImageFormat.cpp \
           $$PWD/PythonQtWrapper_QTextInlineObject.cpp \
           $$PWD/PythonQtWrapper_QTextItem.cpp \
           $$PWD/PythonQtWrapper_QTextLine.cpp \
           $$PWD/PythonQtWrapper_QTextList.cpp \
           $$PWD/PythonQtWrapper_QTextListFormat.cpp \
           $$PWD/PythonQtWrapper_QTextObject.cpp \
           $$PWD/PythonQtWrapper_QTextObjectInterface.cpp \
           $$PWD/PythonQtWrapper_QTextTable.cpp \
           $$PWD/PythonQtWrapper_QTextTableCell.cpp \
           $$PWD/PythonQtWrapper_QTextTableCellFormat.cpp \
           $$PWD/PythonQtWrapper_QTextTableFormat.cpp \
           $$PWD/PythonQtWrapper_QTimeEdit.cpp \
           $$PWD/PythonQtWrapper_QToolBar.cpp \
           $$PWD/PythonQtWrapper_QToolBarChangeEvent.cpp \
           $$PWD/PythonQtWrapper_QToolBox.cpp \
           $$PWD/PythonQtWrapper_QToolButton.cpp \
           $$PWD/PythonQtWrapper_QToolTip.cpp \
           $$PWD/PythonQtWrapper_QTransform.cpp \
           $$PWD/PythonQtWrapper_QTreeView.cpp \
           $$PWD/PythonQtWrapper_QTreeWidget.cpp \
           $$PWD/PythonQtWrapper_QTreeWidgetItem.cpp \
           $$PWD/PythonQtWrapper_QUndoCommand.cpp \
           $$PWD/PythonQtWrapper_QUndoGroup.cpp \
           $$PWD/PythonQtWrapper_QUndoStack.cpp \
           $$PWD/PythonQtWrapper_QUndoView.cpp \
           $$PWD/PythonQtWrapper_QVBoxLayout.cpp \
           $$PWD/PythonQtWrapper_QValidator.cpp \
           $$PWD/PythonQtWrapper_QWhatsThis.cpp \
           $$PWD/PythonQtWrapper_QWhatsThisClickedEvent.cpp \
           $$PWD/PythonQtWrapper_QWheelEvent.cpp \
           $$PWD/PythonQtWrapper_QWidget.cpp \
           $$PWD/PythonQtWrapper_QWidgetAction.cpp \
           $$PWD/PythonQtWrapper_QWidgetItem.cpp \
           $$PWD/PythonQtWrapper_QWindowStateChangeEvent.cpp \
           $$PWD/PythonQtWrapper_QWindowsStyle.cpp \
           $$PWD/PythonQtWrapper_QWizard.cpp \
           $$PWD/PythonQtWrapper_QWizardPage.cpp \
           $$PWD/PythonQtWrapper_QWorkspace.cpp \
           $$PWD/com_trolltech_qt_gui_init.cpp
