name: CMake CI

on:
  push:
    branches:
      - master

jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        qt_version: [5, 6]
        python_version: ["3.8", "3.9", "3.10"]
      fail-fast: false

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python_version }}

      - name: Install dependencies (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y qt${{ matrix.qt_version }}-base qt${{ matrix.qt_version }}-tools

      - name: Install dependencies (Windows)
        if: runner.os == 'Windows'
        run: |
          choco install qt${{ matrix.qt_version }} --version ${{ matrix.qt_version }}.0.0 --params "/InstallationFolder C:/Qt/${{ matrix.qt_version }}"
          echo "C:/Qt/${{ matrix.qt_version }}/bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

      - name: Configure CMake
        run: |
          mkdir build
          cmake -S . -B build \
            -DCMAKE_BUILD_TYPE=Release \
            -DCMAKE_INSTALL_PREFIX=./install

      - name: Build project
        run: |
          cmake --build build --parallel --target all install

      - name: Run tests
        run: |
          cd build
          ctest --output-on-failure